// Generated by scripts/generate-llmswitch-servertool-wrapper.mjs
import type { JsonObject } from '../conversion/hub/types/json.js';

export type NativeChatWebSearchPlan = {
  shouldInject: boolean;
  selectedEngineIndexes: number[];
};

export type NativePayloadContractSignal = {
  reason: string;
  marker: string;
};

export type ServertoolResponseStageToolCallPayload = {
  id: string;
  name: string;
  arguments: string;
};

export type ServertoolResponseStageOutput = {
  providerResponseShape: string;
  isCanonicalChatCompletionPayload: boolean;
  payloadContractSignal?: NativePayloadContractSignal | null;
  normalizedPayload: JsonObject | null;
  toolCalls: ServertoolResponseStageToolCallPayload[];
};

export type ServertoolResponseStageGatePayload = {
  shouldBypass: boolean;
  nextAction: 'bypass' | 'run_auto_hooks' | 'continue_to_execution';
  responseHookMatched: boolean;
  responseHookRequired: boolean;
  responseHookName?: string;
  interceptKind?: string;
  schemaSource?: string;
  skipReason?: string;
};

export type NativeServertoolResponseStageGate = ServertoolResponseStageGatePayload;
export type NativeServertoolResponseStage = ServertoolResponseStageOutput;
export type ServertoolRegistryLookupActionPlan =
  | { action: 'return_builtin'; canonicalName: string }
  | { action: 'return_none' };
export type ServertoolBuiltinHandlerNamesPlan = { names: string[] };
export type ServertoolBuiltinHandlerEntryPlan =
  | { action: 'return_none' }
  | { action: 'return_entry'; entry: Record<string, unknown> };
export type ServertoolBuiltinHandlerEntriesPlan = { entries: Record<string, unknown>[] };
export type ServertoolRegistrationSpec = Record<string, unknown>;
export type ServertoolToolSpec = Record<string, unknown>;
export type ServertoolSkeletonDerivedConfig = Record<string, unknown>;
export type ServertoolDispatchCandidate = {
  id: string;
  name: string;
  arguments: string;
  executionMode: string;
  stripAfterExecute: boolean;
};
export type ServertoolDispatchNoop = {
  id: string;
  name: string;
  arguments: string;
  executionMode?: string;
  stripAfterExecute?: boolean;
};
export type ServertoolDispatchPlan = {
  executableToolCalls: ServertoolDispatchCandidate[];
  noopToolCalls: ServertoolDispatchNoop[];
  skippedToolCalls: Array<{ id: string; name: string; reason: string }>;
};
export type ServertoolDispatchPlanInput = {
  toolCalls: ServertoolResponseStageToolCallPayload[];
  disableToolCallHandlers: boolean;
  includeToolCallHandlerNames?: string[] | null;
  excludeToolCallHandlerNames?: string[] | null;
  registeredToolCallHandlers: Array<{
    name: string;
    trigger: string;
    executionMode: string;
    stripAfterExecute: boolean;
  }>;
  runtimeMetadata?: Record<string, unknown>;
};
export type ServertoolOutcomePlan = {
  outcomeMode: string;
  remainingToolCallIds: string[];
  flowId?: string | null;
  requiresPendingInjection: boolean;
  primaryExecutionMode?: string | null;
};
export type ServertoolOutcomePlanInput = {
  toolCalls: ServertoolResponseStageToolCallPayload[];
  executedToolCalls: ServertoolDispatchCandidate[];
  executedFlowIds: string[];
  lastExecutionFlowId?: string | null;
};
export type ServertoolHandlerContractPlan = { action: string };
export type ServertoolAutoHookPlanEntry<T = Record<string, unknown>> = T & {
  id: string;
  phase: string;
  priority: number;
  order: number;
  sourceIndex?: number;
  queue: 'A_optional' | 'B_mandatory';
  queueIndex: number;
  queueTotal: number;
};
export type ServertoolAutoHookQueues = {
  optionalQueue: ServertoolAutoHookPlanEntry[];
  mandatoryQueue: ServertoolAutoHookPlanEntry[];
  queueOrder: Array<{
    queue: 'A_optional' | 'B_mandatory';
    entries: ServertoolAutoHookPlanEntry[];
  }>;
};
export type ServertoolAutoHookQueueItems<T> = {
  queueOrder: Array<{
    queue: 'A_optional' | 'B_mandatory';
    entries: T[];
  }>;
};
export type ServertoolFollowupRuntimePlan = Record<string, unknown>;
export type ServertoolNoopOutcome = {
  chatResponse: JsonObject;
  flowId: string;
  toolContent: Record<string, unknown>;
};
export type ServertoolProgressEvent = {
  flowId: string;
  tool: string;
  stage: 'entry' | 'trigger' | 'match' | 'hook' | 'compare' | string;
  result: string;
  message: string;
  step: number;
};

export type StopGatewayContext = Record<string, unknown> & {
  observed?: boolean;
  eligible?: boolean;
  source?: 'chat' | 'responses' | 'none' | string;
  reason?: string;
};
export type StopMessageCompareContext = Record<string, unknown>;
export type ServertoolStopGatewayContext = StopGatewayContext;
export type ServertoolStopMessageCompareContext = StopMessageCompareContext;
export type ServertoolRuntimeStopMessageState = Record<string, unknown>;
export type ServertoolTimeoutWatcherPlan = {
  armed: boolean;
  timeoutMs: number;
};
export type NativeServertoolExecutedRecord = Record<string, unknown>;
export type NativeServertoolExecutionLoopState = Record<string, unknown>;
export type ServertoolExecutionLoopState = NativeServertoolExecutionLoopState;
export type ServertoolEngineRuntimeActionPlan = Record<string, unknown>;
export type ServertoolErrorPlan = Record<string, unknown>;

export declare function detectProviderResponseShapeWithNative(payload: unknown): 'openai-chat' | 'openai-responses' | 'anthropic-messages' | 'gemini-chat' | 'unknown';
export declare function containsSyntheticRouteCodexControlTextWithNative(payload: unknown): boolean;

export declare function runServertoolResponseStageWithNative(payload: unknown, requestId: string): NativeServertoolResponseStage;
export declare function planServertoolResponseStageGateWithNative(input: unknown): ServertoolResponseStageGatePayload;

export declare function readServertoolPrimaryAutoHookIdsWithNative(input?: unknown): string[];
export declare function buildServertoolDispatchPlanInputWithNative(input: unknown): ServertoolDispatchPlanInput;

export declare function planServertoolBuiltinAutoHandlerEntriesWithNative(input?: unknown): ServertoolBuiltinHandlerEntriesPlan;

export declare function resolveServertoolRegistryHandlerWithNative(input: unknown): Record<string, unknown> | null;

export declare function resolveServertoolProgressToolNameWithNative(input: unknown): string;
export declare function shouldUseServertoolGoldProgressHighlightWithNative(input: unknown): boolean;
export declare function resolveServertoolProgressStageWithNative(input: unknown): string;
export declare function normalizeServertoolProgressResultWithNative(input: unknown): string;

export declare function normalizeServertoolProgressFlowIdWithNative(input: unknown): string;
export declare function buildServertoolMatchSkippedProgressEventWithNative(input: unknown): ServertoolProgressEvent;
export declare function buildServertoolAutoHookTraceProgressEventWithNative(input: unknown): ServertoolProgressEvent;
export declare function buildServertoolStopEntryProgressEventWithNative(input: unknown): ServertoolProgressEvent;
export declare function buildServertoolStopCompareProgressEventWithNative(input: unknown): ServertoolProgressEvent;
export declare function planServertoolToolCallDispatchWithNative(input: unknown): ServertoolDispatchPlan;

export declare function planServertoolNoopOutcomeWithNative(input: unknown): ServertoolNoopOutcome;

export declare function planServertoolAutoHookQueueItemsWithNative<T>(input: unknown): ServertoolAutoHookQueueItems<T>;

// 18 servertool-core native wrappers consumed by shell files

export declare function inspectStopGatewaySignalWithNative(payload: unknown): ServertoolStopGatewayContext;

export declare function normalizeStopMessageCompareContextWithNative(value: unknown): ServertoolStopMessageCompareContext;
export declare function formatStopMessageCompareContextWithNative(value: unknown): string;

export declare function buildServertoolCliProjectionRuntimeBranchWithNative(input: unknown): Record<string, unknown>;

export declare function planServertoolTimeoutWatcherWithNative(input: unknown): ServertoolTimeoutWatcherPlan;
export declare function isAdapterClientDisconnectedWithNative(adapterContext: unknown): boolean;
export declare function createServertoolExecutionLoopStateWithNative(): ServertoolExecutionLoopState;

export declare function buildServertoolHandlerErrorToolOutputPayloadWithNative(input: unknown): Record<string, unknown>;

export declare function appendServertoolExecutedRecordWithNative(input: unknown): unknown;

export declare function applyServertoolExecutionLoopInitialDecisionWithNative(input: unknown): unknown;
export declare function applyServertoolExecutionLoopResultDecisionWithNative(input: unknown): unknown;

export declare function buildServertoolPostflightObservationSummaryWithNative(input: unknown): unknown;

export declare function createServertoolProviderProtocolErrorFromPlanWithNative(input: unknown): unknown;

export declare function extractServertoolResponseStageOrchestrationShellResultWithNative(input: unknown): unknown;

export declare function finalizeServertoolResponseStageWithNative(input: unknown): unknown;

export declare function materializeNativeToolCallExecutionOutcomeWithNative(input: unknown): unknown;

export declare function materializeServertoolPlannedResultWithNative(planned: unknown, options: { requestId: string }): Promise<unknown>;
export declare function materializeServertoolResponseStageOrchestrationOutputWithNative(input: unknown): unknown;

export declare function planEngineSelectionStartWithNative(input: unknown): unknown;

export declare function planServertoolEnginePreflightWithNative(input: unknown): unknown;

export declare function planServertoolEngineRuntimeActionWithNative(input: unknown): unknown;

export declare function planServertoolEngineTriggerObservationWithNative(input: unknown): unknown;
export declare function planServertoolEntryContextWithNative(input: unknown): unknown;

export declare function planServertoolExecutionDispatchErrorWithNative(input: unknown): unknown;

export declare function planServertoolHandlerErrorExecutionLoopEffectWithNative(input: unknown): unknown;

export declare function planServertoolNoopExecutionLoopEffectWithNative(input: unknown): unknown;

export declare function planServertoolRegistryBuiltinAutoHookEntriesWithNative(input: unknown): unknown;

export declare function planServertoolTimeoutErrorWithNative(input: unknown): unknown;

export declare function planStoplessExecutionWithNative(input: unknown): unknown;

export declare function readServertoolEntryBaseObjectWithNative(input: unknown): unknown;

export declare function resolveAutoHookCallerFinalizationDecisionWithNative(input: unknown): unknown;
export declare function resolveAutoHookRuntimeAttemptDecisionWithNative(input: unknown): unknown;

export declare function resolveEngineSelectionAfterRunWithNative(input: unknown): unknown;

export declare function resolveServertoolEngineMatchHitWithNative(input: unknown): unknown;
export declare function resolveServertoolEngineOrchestrationPreflightDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolEnginePostflightPayloadWithNative(input: unknown): unknown;
export declare function resolveServertoolEnginePreflightDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolEngineSkipDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolEntryPreflightApplicationWithNative(input: unknown): unknown;
export declare function resolveServertoolEntryPreflightWithNative(input: unknown): unknown;
export declare function resolveServertoolExecutionLoopInitialDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolExecutionLoopResultDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolPostExecutionBranchDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolPreExecutionBranchDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolResponseStageAutoHookPostApplicationWithNative(input: unknown): unknown;
export declare function resolveServertoolResponseStageAutoHookPostDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolResponseStageAutoHookPreApplicationWithNative(input: unknown): unknown;
export declare function resolveServertoolResponseStageAutoHookPreDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolResponseStageOrchestrationGateApplicationWithNative(input: unknown): unknown;
export declare function resolveServertoolResponseStagePrepassAfterAutoHookWithNative(input: unknown): unknown;
export declare function resolveServertoolResponseStagePrepassInitialApplicationWithNative(input: unknown): unknown;
export declare function resolveServertoolResponseStagePrepassInitialDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolRunEngineEntryPreflightApplicationWithNative(input: unknown): unknown;
export declare function resolveServertoolRunEngineEntryPreflightDecisionWithNative(input: unknown): unknown;
export declare function resolveServertoolRunEnginePrepassApplicationWithNative(input: unknown): unknown;
export declare function resolveServertoolRunEnginePrepassDecisionWithNative(input: unknown): unknown;

export declare function resolveServertoolTimeoutMsFromEnvCandidatesWithNative(input: unknown): unknown;

export declare function runStoplessBuiltinHandlerForRuntimeWithNative(input: unknown): unknown;
