// Generated by scripts/generate-llmswitch-servertool-wrapper.mjs
import type { JsonObject } from '../conversion/hub/types/json.js';

export type NativeChatWebSearchPlan = {
  shouldInject: boolean;
  selectedEngineIndexes: number[];
};

export type NativePayloadContractSignal = {
  reason: string;
  marker: string;
};

export type ServertoolResponseStageToolCallPayload = {
  id: string;
  name: string;
  arguments: string;
};

export type ServertoolResponseStageOutput = {
  providerResponseShape: string;
  isCanonicalChatCompletionPayload: boolean;
  payloadContractSignal?: NativePayloadContractSignal | null;
  normalizedPayload: JsonObject | null;
  toolCalls: ServertoolResponseStageToolCallPayload[];
};

export type ServertoolResponseStageGatePayload = {
  shouldBypass: boolean;
  nextAction: 'bypass' | 'run_auto_hooks' | 'continue_to_execution';
  responseHookMatched: boolean;
  responseHookRequired: boolean;
  responseHookName?: string;
  interceptKind?: string;
  schemaSource?: string;
  skipReason?: string;
};

export type NativeServertoolResponseStageGate = ServertoolResponseStageGatePayload;
export type NativeServertoolResponseStage = ServertoolResponseStageOutput;
export type ServertoolRegistryLookupActionPlan =
  | { action: 'return_builtin'; canonicalName: string }
  | { action: 'return_none' };
export type ServertoolBuiltinHandlerNamesPlan = { names: string[] };
export type ServertoolBuiltinHandlerEntryPlan =
  | { action: 'return_none' }
  | { action: 'return_entry'; entry: Record<string, unknown> };
export type ServertoolBuiltinHandlerEntriesPlan = { entries: Record<string, unknown>[] };
export type ServertoolRegistrationSpec = Record<string, unknown>;
export type ServertoolToolSpec = Record<string, unknown>;
export type ServertoolSkeletonDerivedConfig = Record<string, unknown>;
export type ServertoolDispatchCandidate = {
  id: string;
  name: string;
  arguments: string;
  executionMode: string;
  stripAfterExecute: boolean;
};
export type ServertoolDispatchNoop = {
  id: string;
  name: string;
  arguments: string;
  executionMode?: string;
  stripAfterExecute?: boolean;
};
export type ServertoolDispatchPlan = {
  executableToolCalls: ServertoolDispatchCandidate[];
  noopToolCalls: ServertoolDispatchNoop[];
  skippedToolCalls: Array<{ id: string; name: string; reason: string }>;
};
export type ServertoolDispatchPlanInput = {
  toolCalls: ServertoolResponseStageToolCallPayload[];
  disableToolCallHandlers: boolean;
  includeToolCallHandlerNames?: string[] | null;
  excludeToolCallHandlerNames?: string[] | null;
  registeredToolCallHandlers: Array<{
    name: string;
    trigger: string;
    executionMode: string;
    stripAfterExecute: boolean;
  }>;
  runtimeMetadata?: Record<string, unknown>;
};
export type ServertoolOutcomePlan = {
  outcomeMode: string;
  remainingToolCallIds: string[];
  flowId?: string | null;
  requiresPendingInjection: boolean;
  primaryExecutionMode?: string | null;
};
export type ServertoolOutcomePlanInput = {
  toolCalls: ServertoolResponseStageToolCallPayload[];
  executedToolCalls: ServertoolDispatchCandidate[];
  executedFlowIds: string[];
  lastExecutionFlowId?: string | null;
};
export type ServertoolHandlerContractPlan = { action: string };
export type ServertoolAutoHookPlanEntry<T = Record<string, unknown>> = T & {
  id: string;
  phase: string;
  priority: number;
  order: number;
  sourceIndex?: number;
  queue: 'A_optional' | 'B_mandatory';
  queueIndex: number;
  queueTotal: number;
};
export type ServertoolAutoHookQueues = {
  optionalQueue: ServertoolAutoHookPlanEntry[];
  mandatoryQueue: ServertoolAutoHookPlanEntry[];
  queueOrder: Array<{
    queue: 'A_optional' | 'B_mandatory';
    entries: ServertoolAutoHookPlanEntry[];
  }>;
};
export type ServertoolAutoHookQueueItems<T> = {
  queueOrder: Array<{
    queue: 'A_optional' | 'B_mandatory';
    entries: T[];
  }>;
};
export type ServertoolFollowupRuntimePlan = Record<string, unknown>;
export type ServertoolNoopOutcome = {
  chatResponse: JsonObject;
  flowId: string;
  toolContent: Record<string, unknown>;
};
export type ServertoolProgressEvent = {
  flowId: string;
  tool: string;
  stage: 'entry' | 'trigger' | 'match' | 'hook' | 'compare' | string;
  result: string;
  message: string;
  step: number;
};

export declare function detectEmptyAssistantPayloadContractSignalWithNative(payload: unknown): NativePayloadContractSignal | null;
export declare function detectProviderResponseShapeWithNative(payload: unknown): 'openai-chat' | 'openai-responses' | 'anthropic-messages' | 'gemini-chat' | 'unknown';
export declare function containsSyntheticRouteCodexControlTextWithNative(payload: unknown): boolean;
export declare function planChatWebSearchOperationsWithNative(request: unknown, runtimeMetadata?: Record<string, unknown>): NativeChatWebSearchPlan;
export declare function runServertoolResponseStageWithNative(payload: unknown, requestId: string): NativeServertoolResponseStage;
export declare function planServertoolResponseStageGateWithNative(input: unknown): ServertoolResponseStageGatePayload;
export declare function planServertoolSkeletonDerivedConfigWithNative(input?: unknown): ServertoolSkeletonDerivedConfig;
export declare function readServertoolPrimaryAutoHookIdsWithNative(input?: unknown): string[];
export declare function buildServertoolDispatchPlanInputWithNative(input: unknown): ServertoolDispatchPlanInput;
export declare function buildServertoolOutcomePlanInputWithNative(input: unknown): ServertoolOutcomePlanInput;
export declare function planServertoolHandlerContractWithNative(input: unknown): ServertoolHandlerContractPlan;
export declare function normalizeServertoolRegistrationSpecWithNative(input: unknown): ServertoolRegistrationSpec | null;
export declare function resolveServertoolToolSpecWithNative(input: unknown): ServertoolToolSpec | null;
export declare function planServertoolBuiltinHandlerEntryWithNative(input: unknown): ServertoolBuiltinHandlerEntryPlan;
export declare function resolveServertoolBuiltinHandlerEntryWithNative(input: unknown): Record<string, unknown> | null;
export declare function planServertoolBuiltinHandlerNamesWithNative(input?: unknown): ServertoolBuiltinHandlerNamesPlan;
export declare function planServertoolBuiltinAutoHandlerEntriesWithNative(input?: unknown): ServertoolBuiltinHandlerEntriesPlan;
export declare function planServertoolBuiltinHandlerRecordEntriesWithNative(input?: unknown): ServertoolBuiltinHandlerEntriesPlan;
export declare function planServertoolRegistryLookupFromSkeletonWithNative(input: unknown): ServertoolRegistryLookupActionPlan;
export declare function resolveServertoolRegistryHandlerWithNative(input: unknown): Record<string, unknown> | null;
export declare function resolveServertoolRegisteredNameWithNative(input: unknown): boolean;
export declare function resolveServertoolProgressToolNameWithNative(input: unknown): string;
export declare function shouldUseServertoolGoldProgressHighlightWithNative(input: unknown): boolean;
export declare function resolveServertoolProgressStageWithNative(input: unknown): string;
export declare function normalizeServertoolProgressResultWithNative(input: unknown): string;
export declare function normalizeServertoolProgressTokenWithNative(input: unknown): string;
export declare function normalizeServertoolProgressFlowIdWithNative(input: unknown): string;
export declare function buildServertoolMatchSkippedProgressEventWithNative(input: unknown): ServertoolProgressEvent;
export declare function buildServertoolAutoHookTraceProgressEventWithNative(input: unknown): ServertoolProgressEvent;
export declare function buildServertoolStopEntryProgressEventWithNative(input: unknown): ServertoolProgressEvent;
export declare function buildServertoolStopCompareProgressEventWithNative(input: unknown): ServertoolProgressEvent;
export declare function planServertoolToolCallDispatchWithNative(input: unknown): ServertoolDispatchPlan;
export declare function planServertoolOutcomeWithNative(input: unknown): ServertoolOutcomePlan;
export declare function planServertoolNoopOutcomeWithNative(input: unknown): ServertoolNoopOutcome;
export declare function planServertoolAutoHookQueuesWithNative(input: unknown): ServertoolAutoHookQueues;
export declare function planServertoolAutoHookQueueItemsWithNative<T>(input: unknown): ServertoolAutoHookQueueItems<T>;

// 18 servertool-core native wrappers consumed by shell files
export declare function extractTextFromChatLikeWithNative(payload: unknown): string;
export declare function inspectStopGatewaySignalWithNative(payload: unknown): ServertoolStopGatewayContext;
export declare function normalizeStopGatewayContextWithNative(value: unknown): ServertoolStopGatewayContext | undefined;
export declare function normalizeStopMessageCompareContextWithNative(value: unknown): ServertoolStopMessageCompareContext;
export declare function formatStopMessageCompareContextWithNative(value: unknown): string;
export declare function resolveRuntimeStopMessageStateWithNative(metadata: unknown): ServertoolRuntimeStopMessageState;
export declare function readRuntimeStopMessageStageModeWithNative(input: unknown): string | undefined;
export declare function parseServertoolCliProjectionToolArgumentsWithNative(input: unknown): unknown;
export declare function buildServertoolCliProjectionExecutionContextWithNative(input: unknown): Record<string, unknown>;
export declare function buildServertoolCliProjectionRuntimeBranchWithNative(input: unknown): Record<string, unknown>;
export declare function resolveRuntimeStopMessageStateFromMetadataCenterWithNative(metadataCenter: unknown): ServertoolRuntimeStopMessageState | null;
export declare function parseServertoolTimeoutMsWithNative(value: unknown): number | undefined;
export declare function planServertoolTimeoutWatcherWithNative(input: unknown): ServertoolTimeoutWatcherPlan;
export declare function isAdapterClientDisconnectedWithNative(adapterContext: unknown): boolean;
export declare function createServertoolExecutionLoopStateWithNative(): ServertoolExecutionLoopState;

export declare function runServertoolOrchestrationMutationWithNative(input: Record<string, unknown>): unknown;
export declare function planServertoolFollowupRuntimeWithNative(flowId: string): ServertoolFollowupRuntimePlan;
export declare function extractCapturedChatSeedWithNative(captured: unknown): Record<string, unknown> | null;
export declare function extractAssistantFollowupMessageWithNative(finalChatResponse: unknown): Record<string, unknown> | null;
export declare function normalizeFollowupParametersWithNative(parameters: unknown): Record<string, unknown> | undefined;
export declare function buildServertoolToolOutputPayloadWithNative(input: unknown): Record<string, unknown>;
export declare function buildServertoolHandlerErrorToolOutputPayloadWithNative(input: unknown): Record<string, unknown>;
export declare function collectServertoolAdditionalClientToolCallsWithNative(input: unknown): unknown[];
export declare function isServertoolClientExecCliProjectionToolCallWithNative(input: unknown): boolean;
export declare function webSearchIsGeminiEngineWithNative(providerKey: string): boolean;
export declare function webSearchIsQwenEngineWithNative(providerKey: string): boolean;
export declare function webSearchIsGlmEngineWithNative(providerKey: string): boolean;
export declare function webSearchNormalizeResultCountWithNative(valueJson: string): number;
export declare function webSearchBuildSystemPromptWithNative(targetCount: number): string;
export declare function webSearchSanitizeBackendErrorWithNative(message: string): string;
export declare function webSearchCollectHitsWithNative(chatResponseJson: string, targetCount: number): string;
export declare function webSearchFormatHitsSummaryWithNative(hitsJson: string): string;
export declare function webSearchLimitHitsWithNative(hitsJson: string): string;
export declare function webSearchExtractAssistantMessageWithNative(chatResponseJson: string): string;
export declare function webSearchBuildToolMessagesWithNative(chatResponseJson: string): string;
export declare function visionBuildAnalysisPayloadWithNative(sourceJson: string): string;
export declare function visionBuildPinnedMetadataWithNative(adapterContextJson: string, payloadJson: string): string;
export declare function visionExtractOriginalUserPromptWithNative(messagesJson: string): string;