// Generated by scripts/generate-llmswitch-servertool-wrapper.mjs
// Servertool runtime semantics are Rust-owned. This package subpath intentionally
// exposes no per-capability native wrapper declarations.
export {};
