import fs from 'node:fs';
import path from 'node:path';

const DELETED_FILES = [
  'sharedmodule/llmswitch-core/src/servertool/execution-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/execution-dispatch-outcome-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry-impl.ts',
  'sharedmodule/llmswitch-core/src/servertool/adhoc-handler-test-support.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry-registration-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry-projection-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry-types.ts',
  'sharedmodule/llmswitch-core/src/servertool/builtin-handler-catalog.ts',
  'sharedmodule/llmswitch-core/src/servertool/pre-command-hooks.ts',
  'sharedmodule/llmswitch-core/src/servertool/pre-command-runtime-state-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/pending-session.ts',
  'sharedmodule/llmswitch-core/src/servertool/pending-injection-block.ts',
  'sharedmodule/llmswitch-core/src/servertool/skeleton-config.ts',
  'sharedmodule/llmswitch-core/src/servertool/orchestration-policy-block.ts',
  'sharedmodule/llmswitch-core/src/servertool/cli-projection-runtime-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/execution-handler-materialization-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/engine.ts',
  'tests/servertool/cli-projection-runtime-shell.spec.ts',
  'tests/servertool/execution-handler-materialization-shell.spec.ts',
  'sharedmodule/llmswitch-core/rust-core/crates/servertool-core/src/pre_command_hook_contract.rs',
  'sharedmodule/llmswitch-core/rust-core/crates/servertool-core/src/pending_session_contract.rs',
] as const;

const TARGETS = [
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/types.ts',
    forbidden: [
      'providerProtocol: string;\n  disableToolCallHandlers?: boolean;',
      'providerProtocol: string;\n  runtimeMetadata?: JsonObject;',
    ],
    required: [
      'export interface ServerSideToolEngineOptions',
      'export interface ServerToolHandlerContext',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-queue-shell.ts',
    forbidden: [
      '  ToolCall\n} from \'./types.js\';',
      "String(lastErr ?? 'unknown')",
      "lastErr instanceof Error ? lastErr.message : String",
      'lastErr instanceof Error ? lastErr.message : lastErr',
      'Boolean(lastErr)',
      'Boolean(entry)',
      'Boolean(result)',
      'planned ? await materializeServertoolPlannedResult',
      "nativeExecutionMode: entry?.registration.executionMode ?? ''",
      "toolCall: errorEffectPlan.toolCall as NativeServertoolExecutedRecord['toolCall']",
      'execution: errorEffectPlan.execution as ServerToolExecution',
      "toolCall: noopEffectPlan.toolCall as NativeServertoolExecutedRecord['toolCall']",
      'execution: noopEffectPlan.execution as ServerToolExecution',
      'result.chatResponse as JsonObject',
      'noopResult.chatResponse as JsonObject',
      'buildServertoolHandlerErrorToolOutputPayloadWithNative({\n          base: args.baseForExecution as Record<string, unknown>,\n          toolCallId: toolCall.id,\n          toolName: toolCall.name,\n          message: errorEffectPlan.handlerErrorMessage\n        }) as JsonObject',
      'base: args.baseForExecution as Record<string, unknown>',
      "if (initialLoopActionPlan.action === 'skip_non_tool_call_handler')",
      "if (initialLoopActionPlan.action === 'throw_dispatch_spec_mismatch')",
      "if (resultLoopActionPlan.action === 'apply_materialized_result')",
      "if (resultLoopActionPlan.action === 'apply_handler_error_tool_output')",
      'initialLoopDecision.action',
      'resultLoopDecision.action',
      'const initialLoopAction = initialLoopActionPlan.action',
      'const resultLoopAction = resultLoopActionPlan.action',
      'planServertoolExecutionLoopRuntimeActionWithNative',
      'switch (initialLoopActionPlan.action)',
      'switch (resultLoopActionPlan.action)',
      'String(initialLoopActionPlan.action)',
      'String(resultLoopActionPlan.action)',
      'errorEffectPlan.handlerErrorMessage as string',
      "mode: 'handler_error'",
      "mode: 'noop'",
      'flowId: noopFlowId',
      'noopFlowId',
    ],
    required: [
      'runServertoolIoExecutionQueue',
      'resolveServertoolExecutionLoopInitialDecisionWithNative',
      'resolveServertoolExecutionLoopResultDecisionWithNative',
      'applyServertoolExecutionLoopInitialDecisionWithNative',
      'applyServertoolExecutionLoopResultDecisionWithNative',
      'createServertoolExecutionLoopStateWithNative',
      'appendServertoolExecutedRecordWithNative',
      'createServertoolProviderProtocolErrorFromPlan',
      'hasHandlerEntry: entry != null',
      'nativeExecutionMode: entry.registration.executionMode',
      'planned != null ? await materializeServertoolPlannedResult',
      'hasMaterializedResult: result != null',
      'replaceJsonObjectInPlace(args.baseForExecution, result.chatResponse)',
      'replaceJsonObjectInPlace(args.baseForExecution, noopResult.chatResponse)',
      'const toolOutputPayload = buildServertoolHandlerErrorToolOutputPayloadWithNative({',
      'base: args.baseForExecution',
      'message: errorEffectPlan.handlerErrorMessage',
      'planServertoolHandlerErrorExecutionLoopEffectWithNative',
      'planServertoolNoopExecutionLoopEffectWithNative',
      'toolCall: errorEffectPlan.toolCall',
      'execution: errorEffectPlan.execution',
      'toolCall: noopEffectPlan.toolCall',
      'execution: noopEffectPlan.execution',
      'noopOutcome: noopResult',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/timeout-error-block.ts',
    forbidden: [
      'export function createServerToolTimeoutError(',
      'export function createServertoolRequiredResponseHookEmptyError(',
      'export function createServerToolClientDisconnectedError(',
    ],
    required: [
      'export function createServertoolProviderProtocolErrorFromPlan(',
      'planServertoolTimeoutWatcherWithNative',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/auto-hook-caller.ts',
    forbidden: [
      "outcome: 'error'",
      "outcome: 'planned_null'",
      "outcome: 'materialized_match'",
      "outcome: 'materialized_empty'",
      "result: 'error'",
      "reason: 'predicate_false'",
      "reason: 'matched_without_flow'",
      "reason: 'empty_materialized_result'",
      'errorAttemptInput',
      'runtimeAttemptInput',
      'callerFinalizationInput',
      'if (planned) {',
      'if (!planned) {',
      'planned as any',
      'if (attemptPlan.returnResult)',
      'switch (attemptPlan.returnResult)',
      'if (result) {',
      'if (!result)',
      'return result as ServerToolHandlerResult',
      'if (!queueResult)',
      'result?.execution && typeof result.execution.flowId',
      'queueResultForReturn.metadataWritePlan ?',
      'const queueResultForReturn = queueResult as ServerToolHandlerResult',
      'native auto-hook execution requested result but materialization was empty',
      'native auto-hook queue progress requested result but queue result was empty',
      'native auto-hook execution returned no materialized disposition',
      'if (optionalResult) {',
      'result.execution.flowId.trim()',
      'if (mandatoryResult) {',
      'const toolFlowResult: ServerSideToolEngineResult = {',
      'return toolFlowResult;',
      'export async function runAutoHookExecutionQueue(',
      'ServerToolHandlerPlan',
      'function planAutoHookRuntimeAttempt(',
      'const attemptPlan = planAutoHookRuntimeAttempt({',
      'attemptPlan as { action: unknown }',
      'function planAutoHookCallerFinalization(',
      'const finalizationPlan = planAutoHookCallerFinalization({',
      'attemptPlan.traceEvent as ServerToolAutoHookTraceEvent',
      'if (finalizationPlan.returnResult)',
      'if (finalizationPlan.continueNextQueue)',
      'if (finalizationPlan.returnNull)',
      'mode: finalizationPlan.resultMode',
      'const finalQueueName = queueOrder[queueOrder.length - 1]?.queueName;',
      'const finalQueue = queue.queueName === finalQueueName;',
      'finalQueue',
      "String(error ?? 'unknown')",
      'error instanceof Error ? error.message : String',
      "typeof error === 'string' ? error",
      'planServertoolAutoHookQueuesWithNative({',
      'planServertoolSkeletonDerivedConfigWithNative',
      'autoHookQueueConfig as',
      'optionalPrimaryHookOrder',
      'mandatoryHookOrder',
      'args.hooks[entry.sourceIndex]',
      'native auto-hook queue returned invalid sourceIndex',
      'type AutoHookExecutionItem =',
      'hooks: args.hooks.map((hook)',
      'execution: hook.execution',
      "mode: 'tool_flow'",
      'finalizationPlan as { action: string }',
      'const attemptPlan = planAutoHookRuntimeAttemptWithNative({',
      'const finalizationPlan = planAutoHookCallerFinalizationWithNative({',
      'switch (attemptPlan.action)',
      'switch (finalizationPlan.action)',
      'return finalizationPlan.result;',
      "attemptDecision.action === 'rethrow_error'",
      "attemptDecision.action === 'return_result'",
      "attemptDecision.action !== 'continue_queue'",
      "finalizationDecision.action === 'return_result'",
      "finalizationDecision.action === 'return_null'",
      "finalizationDecision.action !== 'continue_next_queue'",
    ],
    required: [
      'const attemptDecision = resolveAutoHookRuntimeAttemptDecisionWithNative({',
      'const result = planned != null',
      'await materializeServertoolPlannedResult(planned, args.options)',
      'planServertoolAutoHookQueueItemsWithNative({',
      'const finalizationDecision = resolveAutoHookCallerFinalizationDecisionWithNative({',
      'if (!attemptDecision.continueQueue)',
      'if (attemptDecision.returnResult)',
      'if (attemptDecision.rethrowError)',
      'result?.execution != null && typeof result.execution.flowId',
      'if (result == null)',
      'return result;',
      'metadataWritePlanPresent: queueResult?.metadataWritePlan != null',
      'chatResponse: queueResult?.chatResponse',
      'execution: queueResult?.execution',
      'metadataWritePlan: queueResult?.metadataWritePlan',
      'queueIndex: queueIndex + 1',
      'queueTotal: queueOrder.length',
      'return finalizationDecision.result;',
      'if (finalizationDecision.result == null)',
      'if (finalizationDecision.returnNull)',
      'if (!finalizationDecision.continueNextQueue)',
      'invalid auto-hook attempt action',
      'invalid auto-hook caller finalization action',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-finalize-shell.ts',
    forbidden: [
      "const passthroughResult = { mode: 'passthrough', finalChatResponse: args.baseObject } as const;",
      'return passthroughResult;',
      'initialResponseStageGatePlan',
      'planServertoolResponseStageGateWithNative',
      'readRuntimeControlFromAnyBoundMetadataCenter',
      'responseHookMatched === true',
      "responseStageAutoHook.action === 'return_passthrough_bypass'",
      "if (finalizeRuntimeAction.action === 'return_auto_hook_result')",
      "return { mode: 'passthrough', finalChatResponse: args.baseObject };",
      'mode: finalizeRuntimeAction.resultMode',
      'finalizeRuntimeAction as { action: string }',
      'autoHookResult == null',
      'autoHookResult as ServerSideToolEngineResult',
      'native response-stage finalize requested auto-hook result but result was empty',
      'responseStageGatePlan: Record<string, unknown>',
      'return responseStageAutoHook.result',
      'return finalizeRuntimeAction.passthroughResult as ServerSideToolEngineResult',
      'planServertoolResponseStageRuntimeActionWithNative',
      'switch (finalizeRuntimeAction.action)',
      "hasAutoHookResult: responseStageAutoHook.action === 'return_auto_hook_result'",
      'autoHookResult: responseStageAutoHook.action ===',
      'return finalizeRuntimeAction.finalizeResult',
      'invalid response-stage finalize action',
    ],
    required: [
      "contextBase: Omit<ServerToolHandlerContext, 'toolCall'>",
      'NativeServertoolResponseStageGate',
      'runServertoolResponseStageAutoHookPass',
      'responseStageGatePlan: args.responseStageGatePlan',
      'baseObject: args.baseObject',
      'finalizeServertoolResponseStageWithNative({',
      'responseStageAutoHookResult: responseStageAutoHook',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-auto-hook-shell.ts',
    forbidden: [
      "if (preAutoHookRuntimeAction.action === 'return_passthrough_bypass')",
      "if (postAutoHookRuntimeAction.action === 'return_required_response_hook_empty')",
      "if (postAutoHookRuntimeAction.action === 'return_auto_hook_result')",
      "return { action: 'return_passthrough_bypass' }",
      "return { action: 'continue_without_result' }",
      "action: 'return_auto_hook_result',",
      'result: autoHookResult as ServerSideToolEngineResult',
      'responseHookName: postAutoHookRuntimeAction.responseHookName as string',
      'preAutoHookRuntimeAction as { action: string }',
      'postAutoHookRuntimeAction as { action: string }',
      'switch (preAutoHookRuntimeAction.action)',
      'switch (postAutoHookRuntimeAction.action)',
      'return preAutoHookRuntimeAction.passResult',
      'return postAutoHookRuntimeAction.passResult',
      'responseHookName: postAutoHookRuntimeAction.responseHookName',
      "preAutoHookDecision.action === 'return_pass_result'",
      "postAutoHookDecision.action === 'throw_required_response_hook_empty'",
      'hasAutoHookResult: autoHookResult != null',
      'if (autoHookResult == null)',
      'invalid response-stage pre auto-hook action',
      'invalid response-stage post auto-hook action',
      'function hasServerSideToolEngineResult(',
      'hasServerSideToolEngineResult(autoHookResult)',
    ],
    required: [
      'resolveServertoolResponseStageAutoHookPreDecisionWithNative',
      'resolveServertoolResponseStageAutoHookPostDecisionWithNative',
      'resolveServertoolResponseStageAutoHookPreApplicationWithNative',
      'resolveServertoolResponseStageAutoHookPostApplicationWithNative',
      'autoHookResult',
      'preAutoHookApplication.returnPassResult',
      'postAutoHookApplication.throwRequiredResponseHookEmpty',
      'return preAutoHookApplication.result',
      'return postAutoHookApplication.result',
      'createServertoolProviderProtocolErrorFromPlan(postAutoHookApplication.errorPlan)',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-prepass-shell.ts',
    forbidden: [
      'responseHookMatched !== true',
      'responseStageGatePlan.responseHookMatched !== true',
      "prepassRuntimeAction.action !== 'run_auto_hooks'",
      "if (responseStageAutoHook.action === 'return_auto_hook_result')",
      'autoHookResult as ServerSideToolEngineResult',
      'prepassRuntimeAction as { action: string }',
      "prepassDecision.action === 'return_prepass_result'",
      'responseStageAutoHook as { action: string }',
      '}) as Record<string, unknown>',
      'args.options.adapterContext as Record<string, unknown>',
      'responseStageGatePlan: Record<string, unknown>',
      "action: 'continue_to_execution' as const",
      'planServertoolResponseStageRuntimeActionWithNative',
      'switch (prepassRuntimeAction.action)',
      'switch (responseStageAutoHook.action)',
      'postAutoHookRuntimeAction.prepassResult',
      'invalid response-stage prepass action',
      'invalid response-stage prepass auto-hook action',
    ],
    required: [
      'planServertoolResponseStageGateWithNative',
      'NativeServertoolResponseStageGate',
      'resolveServertoolResponseStagePrepassInitialDecisionWithNative',
      'resolveServertoolResponseStagePrepassInitialApplicationWithNative',
      'resolveServertoolResponseStagePrepassAfterAutoHookWithNative',
      'runServertoolResponseStageAutoHookPass',
      'responseStageGatePlan',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/extract-tool-calls-shell.ts',
    forbidden: [
      'function asObject(',
      "stage.normalizedPayload && typeof stage.normalizedPayload === 'object'",
      'stage.normalizedPayload as JsonObject',
    ],
    required: [
      'runServertoolResponseStageWithNative',
      'replaceJsonObjectInPlace',
      "stage.normalizedPayload != null && typeof stage.normalizedPayload === 'object'",
      '? stage.normalizedPayload',
      'stage.toolCalls.map(',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/dispatch-preparation-shell.ts',
    forbidden: [
      "from '../conversion/runtime-metadata.js'",
      'readRuntimeMetadata(',
      'resolveServertoolRuntimePreCommandState',
      'applyPreCommandHooksToToolCalls',
      'buildServertoolDispatchPlanInput(',
      '...(args.includeToolCallNames ? { includeToolCallHandlerNames: [...args.includeToolCallNames] } : {})',
      '...(args.excludeToolCallNames ? { excludeToolCallHandlerNames: [...args.excludeToolCallNames] } : {})',
      'baseObject: JsonObject;',
      'baseForExecution: JsonObject;',
      'readProviderProtocolFromAnyBoundMetadataCenter',
      'Servertool dispatch preparation requires metadata center runtime_control.providerProtocol',
      'args.options.adapterContext as Record<string, unknown>',
    ],
    required: [
      'readRuntimeMetadataSnapshotFromAnyBoundMetadataCenter',
      'planServertoolToolCallDispatchWithNative',
      'buildServertoolDispatchPlanInputWithNative',
      'dispatchPlan: planServertoolToolCallDispatchWithNative(',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/entry-preflight-shell.ts',
    forbidden: [
      'createServerToolClientDisconnectedError',
      "if (entryPreflightPlan.action === 'return_passthrough_non_object_chat')",
      "if (entryPreflightPlan.action === 'throw_client_disconnected')",
      "args.options.chatResponse && typeof args.options.chatResponse === 'object'",
      "args.options.chatResponse != null && typeof args.options.chatResponse === 'object'",
      'args.options.chatResponse as JsonObject',
      'base as JsonObject',
      'entryPreflightPlan as { action: unknown }',
      'result: { mode: entryPreflightPlan.resultMode, finalChatResponse: args.options.chatResponse }',
      'entryPreflightPlan.resultMode',
      "result: { mode: 'passthrough', finalChatResponse: args.options.chatResponse }",
      'switch (entryPreflightPlan.action)',
      'result: entryPreflightPlan.passthroughResult as ServerSideToolEngineResult',
      'planServertoolClientDisconnectedErrorWithNative',
      "entryPreflightDecision.action === 'throw_error'",
      'entryPreflightDecision.errorPlan',
    ],
    required: [
      'resolveServertoolEntryPreflightWithNative',
      'resolveServertoolEntryPreflightApplicationWithNative',
      'readServertoolEntryBaseObjectWithNative(args.options.chatResponse)',
      'createServertoolProviderProtocolErrorFromPlan',
      'chatResponse: args.options.chatResponse',
      'entryPreflightApplication.errorPlan',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/engine-preflight-shell.ts',
    forbidden: [
      'stopSignal.observed && preflightAction.action',
      'if (stopSignal.observed) {',
      "if (preflightAction.action === 'return_original_chat')",
      "if (preflightAction.action === 'return_original_chat_direct_passthrough')",
      "case 'return_original_chat'",
      "case 'return_original_chat_direct_passthrough'",
      "case 'continue_to_engine'",
      'preflightAction.logStopEntry.stage',
      'preflightAction.logStopEntry.result',
      'String(preflightAction.action)',
      'args.adapterContext as Record<string, unknown>',
    ],
    required: [
      'runEnginePreflight',
      'function runPreflightSideEffects(',
      'planServertoolEnginePreflightWithNative',
      'resolveServertoolEnginePreflightDecisionWithNative',
      'inspectStopGatewaySignal(',
      'attachStopGatewayContext(',
      'containsSyntheticRouteCodexControlTextWithNative(',
      'preflightAction.attachStopGatewayContext === true',
      'preflightAction.logStopEntry',
      'preflightAction.logStopCompare',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/entry-context-shell.ts',
    forbidden: [
      'export function asServertoolJsonObject(',
      'readProviderProtocolFromAnyBoundMetadataCenter',
      'Servertool entry context requires metadata center runtime_control.providerProtocol',
      "action: 'return_non_object_base'",
      'if (!args.base)',
      'entryContextPlan.includeToolCallNames.length > 0',
      'entryContextPlan.excludeToolCallNames.length > 0',
      'entryContextPlan.includeAutoHookIds.length > 0',
      'entryContextPlan.excludeAutoHookIds.length > 0',
      'args.options.adapterContext as Record<string, unknown>',
      'return tokens ? new Set(tokens) : null;',
    ],
    required: [
      'resolveServertoolEntryContext',
      'planServertoolEntryContextWithNative',
      'return tokens != null ? new Set(tokens) : null;',
      'const includeToolCallNames =',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/engine-selection-block.ts',
    forbidden: [
      'primaryAutoHookIds.length',
      'engineResult.mode',
      '!engineResult.execution',
      "mode === 'passthrough'",
      'function toEngineOverrides(',
      'planServertoolSkeletonDerivedConfigWithNative',
      'autoHookQueueConfig as',
      'optionalPrimaryOrder: string[]',
      'primaryAutoHookAttempt:',
      'disableToolCallHandlers: true',
      'includeAutoHookIds: primaryAutoHookIds',
      'excludeAutoHookIds: primaryAutoHookIds',
      'typeof startPlan.overrides.disableToolCallHandlers',
      'Array.isArray(startPlan.overrides.includeAutoHookIds)',
      'Array.isArray(startPlan.overrides.excludeAutoHookIds)',
      'typeof overrides.disableToolCallHandlers',
      'Array.isArray(overrides.includeAutoHookIds)',
      'Array.isArray(overrides.excludeAutoHookIds)',
      "if (afterRunPlan.action === 'rerun_excluding_primary_hooks')",
      'String(afterRunPlan.action)',
      'afterRunPlan.overrides ?? {}',
      'switch (afterRunPlan.action)',
      'return await args.runEngine(afterRunPlan.overrides);',
      "[servertool] invalid engine selection action",
    ],
    required: [
      'readServertoolPrimaryAutoHookIdsWithNative',
      'planEngineSelectionStartWithNative',
      'resolveEngineSelectionAfterRunWithNative',
      'const engineResult = await args.runEngine(startPlan.overrides);',
      'return await args.runEngine(afterRunDecision.rerunOverrides);',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/run-server-side-tool-engine-shell.ts',
    forbidden: [
      "const passthroughResult = { mode: 'passthrough', finalChatResponse: options.chatResponse } as const;",
      "import type { JsonObject } from '../conversion/hub/types/json.js';",
      "if (entryPreflight.action === 'return_result')",
      "if (entryContext.action !== 'continue')",
      "case 'return_non_object_base':",
      'invalid entry context action',
      "if (responseStagePrePass.action === 'return_result')",
      'const entryPreflightAction = entryPreflight.action',
      'const entryContextAction = entryContext.action',
      'const responseStagePrePassAction = responseStagePrePass.action',
      "entryPreflightDecision.action === 'return_result'",
      "enginePrepassDecision.action === 'return_result'",
      'entryPreflight as { action: unknown }',
      'enginePrepassAction as { action: unknown }',
      'planServertoolEnginePrepassActionWithNative',
      'switch (entryPreflight.action)',
      'switch (enginePrepassAction.action)',
      'contextBase: entryContext.contextBase as ServerToolHandlerContext',
    ],
    required: [
      'orchestrateServertoolEngine',
      'runServertoolEntryPreflight',
      'extractToolCallsFromResponseStage',
      'resolveServertoolEntryContext',
      'runServertoolResponseStagePrePass',
      'runServertoolExecutionStage',
      'resolveServertoolRunEngineEntryPreflightDecisionWithNative',
      'resolveServertoolRunEngineEntryPreflightApplicationWithNative',
      'resolveServertoolRunEnginePrepassDecisionWithNative',
      'resolveServertoolRunEnginePrepassApplicationWithNative',
      'contextBase: entryContext.contextBase',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-stage-shell.ts',
    forbidden: [
      'structuredClone(args.baseObject)',
      'const baseForExecution = structuredClone',
      'const baseForExecution = args.baseObject;',
      'isStopMessageAutoPreProjection',
      'filterOutExecutedToolCalls',
      'stripToolOutputs',
      'function planExecutionBranchRuntimeAction(',
      'const preExecutionBranchPlan = planExecutionBranchRuntimeAction({',
      'const postExecutionBranchPlan = planExecutionBranchRuntimeAction({',
      'const preExecutionBranchPlan = planServertoolExecutionBranchWithNative({',
      'const postExecutionBranchPlan = planServertoolExecutionBranchWithNative({',
      ['switch (preExecutionBranchPlan', 'action)'].join('.'),
      ['switch (postExecutionBranchPlan', 'action)'].join('.'),
      ['if (preExecutionBranchPlan', "action === 'client_exec_cli_projection')"].join('.'),
      ['if (postExecutionBranchPlan', "action === 'resolve_execution_outcome')"].join('.'),
      ['if (preExecutionBranchDecision', "action === 'client_exec_cli_projection')"].join('.'),
      ['if (preExecutionBranchDecision', "action !== 'continue_response_stage')"].join('.'),
      ['if (postExecutionBranchDecision', "action === 'resolve_execution_outcome')"].join('.'),
      ['if (postExecutionBranchDecision', "action !== 'continue_response_stage')"].join('.'),
      'if (!projectedToolCall)',
      'native execution-branch projected missing tool call',
      ['String(preExecutionBranchPlan', 'action)'].join('.'),
      ['String(postExecutionBranchPlan', 'action)'].join('.'),
      'contextBase: args.contextBase as ServerToolHandlerContext',
      '}\n\n  return finalizeServertoolResponseStage({',
    ],
    required: [
      'prepareServertoolDispatchStage',
      'resolveServertoolPreExecutionBranchDecisionWithNative',
      'resolveServertoolPostExecutionBranchDecisionWithNative',
      'const preExecutionBranchDecision = resolveServertoolPreExecutionBranchDecisionWithNative({',
      'const postExecutionBranchDecision = resolveServertoolPostExecutionBranchDecisionWithNative({',
      'preExecutionBranchDecision.projectClientExecCli',
      'preExecutionBranchDecision.continueResponseStage',
      'postExecutionBranchDecision.resolveExecutionOutcome',
      'postExecutionBranchDecision.continueResponseStage',
      'invalid pre-execution branch action',
      'invalid post-execution branch action',
      'runServertoolIoExecutionQueue',
      'materializeNativeToolCallExecutionOutcome',
      'finalizeServertoolResponseStage',
      'contextBase: args.contextBase',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-orchestration-shell.ts',
    forbidden: [
      "from './server-side-tools-impl.js'",
      'runServertoolResponseStageWithNative',
      'const responseStage =',
      'readFollowupClientInjectSourceWithNative',
      'writeRuntimeControlToBoundMetadataCenter(',
      'servertoolResponseOrchestration',
      'providerProtocol: ProviderProtocol;',
      'const providerProtocol =',
      'Servertool response stage orchestration requires metadata center runtime_control.providerProtocol',
      'function planServertoolResponseStageGate(',
      'const gatePlan = planServertoolResponseStageGate({',
      "gatePlan.skipReason || 'followup_bypass'",
      "gatePlan.skipReason === 'no_servertool_support'",
      "gatePlan.skipReason === 'followup_bypass'",
      "throw new Error('[servertool] native response-stage gate bypass missing skipReason')",
      'typeof gatePlan.skipReason',
      'gatePlan.skipReason.trim()',
      'gatePlan.skipReason as string',
      "gatePlan.nextAction === 'bypass'",
      "if (gateRuntimeAction.action === 'return_passthrough_bypass')",
      'String(gateRuntimeAction.action)',
      'switch (gateRuntimeAction.action)',
      "case 'return_passthrough_bypass'",
      'const skipReason = gateRuntimeAction.skipReason',
      'planServertoolResponseStageRuntimeActionWithNative',
      'resolveServertoolResponseStageOrchestrationGateDecisionWithNative',
      'String(outputPlan.returnAction)',
      'if (orchestration.executed)',
      'chat: options.payload as JsonObject',
    ],
    required: [
      'const gatePlan = planServertoolResponseStageGateWithNative({',
      'resolveServertoolResponseStageOrchestrationGateApplicationWithNative',
      'if (gateApplication.bypass)',
      'detectProviderResponseShapeWithNative',
      'const orchestration = await runServerToolOrchestrationShell(',
      'runServerToolOrchestrationShell',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-stage-shell.ts',
    forbidden: [
      "from './cli-projection-runtime-shell.js'",
      'buildServertoolCliProjectionBranchResult',
      'toolCall.id === preExecutionBranchPlan.projectedToolCallId',
      'preExecutionBranchPlan.projectedToolCallIndex',
      'dispatchPlan.executableToolCalls[preExecutionBranchPlan.projectedToolCallIndex]',
      'if (!projectedToolCall)',
      'native execution-branch projected missing tool call',
      '.find(isClientExecCliProjectionToolCall)',
      'export function isClientExecCliProjectionToolCall(',
      'export const collectAdditionalClientToolCalls',
      'function parseToolArguments(',
      'JSON.parse(value)',
      'const projectionShellInput = {',
      'buildClientVisibleProjectionShellWithNative(projectionShellInput)',
      'function buildClientVisibleProjectionShellForRuntime(',
      'const projectionInput = parseServertoolCliProjectionToolArgumentsWithNative({',
      'input: parseServertoolCliProjectionToolArgumentsWithNative({',
      'input: projectionInput',
      'const nativeProjection = buildClientExecCliProjectionOutputWithNative({',
      'buildClientExecCliProjectionOutputWithNative',
      'const chatResponse = buildClientVisibleProjectionShellWithNative({',
      'buildClientVisibleProjectionShellWithNative',
      'const execution = buildServertoolCliProjectionExecutionContextWithNative({',
      'buildServertoolCliProjectionExecutionContextWithNative',
      'randomUUID',
      'servertool_cli_projection',
      'reasoningText',
      '继续执行本地 hook',
      "mode: 'tool_flow'",
      'finalChatResponse: branch.chatResponse as JsonObject',
      'finalChatResponse: branch.chatResponse',
      'execution: branch.execution as {',
      'execution: branch.execution',
      'mode: branch.resultMode',
    ],
    required: [
      'buildServertoolCliProjectionRuntimeBranchWithNative({',
      'const projectedToolCall = preExecutionBranchDecision.projectedToolCall',
      'return branch.result',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/engine-postflight-shell.ts',
    forbidden: [
      'function applyServertoolPostflightMetadataWritePlan(',
      'function buildStoplessProjectionMetadataCenterSnapshot(',
      'function printServertoolLine(',
      "symbol: 'applyServertoolPostflightMetadataWritePlan'",
      'const followupSummary: Record<string, unknown> = {',
      "if ('payload' in followup)",
      'payloadRecord.messages',
      'payloadRecord.input',
      "if ('injection' in followup)",
      'followup.injection?.ops',
      'const engineFinalResult = {',
      'return engineFinalResult;',
      'const requestTruth = metadataCenterSnapshot?.requestTruth',
      'const rawSessionId = requestTruth?.sessionId',
      'rawSessionId.trim()',
      'String((args.runtimeAction as { flowIdSource: unknown }).flowIdSource)',
      'runtimeAction.flowIdSource',
      'engineResult.execution?.flowId',
      'function resolvePostflightFlowId(',
      'resolvePostflightFlowId({',
      'switch (runtimeAction.action)',
      "if (runtimeAction.action === 'return_servertool_cli_projection_final')",
      "if (runtimeAction.action === 'return_stop_message_terminal_final')",
      "if (runtimeAction.action === 'build_stop_message_cli_projection')",
      "'completed (servertool cli projection; no reenter)'",
      "'completed (stop_message terminal)'",
      "'completed (stop_message cli projection; no reenter)'",
      "engineResult.metadataWritePlan && typeof engineResult.metadataWritePlan === 'object'",
      'projectNativeMetadataWritePlanToRuntimeControl(',
      'Object.keys(runtimeControl).length',
      'executed: true',
      'const projectedFlowId = runtimeAction.projectedFlowId;',
      'switch (runtimeAction.finalPayloadSource)',
      "case 'engine_result'",
      "case 'stop_message_cli_projection'",
      'chat = engineResult.finalChatResponse',
    ],
    required: [
      'resolveServertoolEnginePostflightPayloadWithNative({',
      'buildServertoolPostflightObservationSummaryWithNative({',
      "args.stageRecorder.record('servertool.execution', summary);",
      'projectNativeMetadataWritePlanToRuntimeControlWritePlan(engineResult.metadataWritePlan)',
      "engineResult.metadataWritePlan != null && typeof engineResult.metadataWritePlan === 'object'",
      'executed: runtimeAction.executed',
      'runtimeAction.progressStatus',
      'flowId: runtimeAction.projectedFlowId',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/progress-log-block.ts',
    forbidden: [
      'function resolveStage(',
      'function normalizeResult(',
      'event.reason.trim().toLowerCase().replace',
      'compareContext.reason.toLowerCase().replace',
      'extra.flowId.trim()',
      'flowId.trim()',
      'readProviderProtocolFromAnyBoundMetadataCenter(args.adapterContext as Record<string, unknown>)',
      'readProviderProtocolFromAnyBoundMetadataCenter(args.adapterContext as Record<string, unknown> | undefined)',
    ],
    required: [
      'normalizeServertoolProgressFlowIdWithNative({ value: extra?.flowId })',
      'resolveServertoolProgressStageWithNative({ step, message })',
      'normalizeServertoolProgressResultWithNative({ message })',
      'buildServertoolAutoHookTraceProgressEventWithNative(event)',
      'buildServertoolStopEntryProgressEventWithNative({',
      'buildServertoolStopCompareProgressEventWithNative({',
      'export function appendServertoolMatchSkippedProgressEvent(',
      'readProviderProtocolFromAnyBoundMetadataCenter(args.adapterContext',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/engine-orchestration-shell.ts',
    forbidden: [
      'const stoplessExecutionInput = {',
      'const hasServertoolCliProjectionContext =',
      'function planStoplessEngineRuntime(',
      'const { stoplessExecution, runtimeAction } = planStoplessEngineRuntime({',
      'planStoplessExecutionWithNative(stoplessExecutionInput)',
      'const postflightEngineResult = {',
      'engineResult: postflightEngineResult,',
      'function createServerToolEngineRunner(',
      'type ServerToolEngineRunner =',
      "from './orchestration-policy-block.js'",
      'readProviderProtocolFromAnyBoundMetadataCenter',
      'providerProtocol: args.providerProtocol',
      'Servertool engine orchestration requires metadata center runtime_control.providerProtocol',
      'parseServertoolTimeoutMsWithNative({ raw: raw || undefined })',
      '.map((key) => process.env[key]).find((value) => Boolean(value))',
      "if (preflight.kind === 'return_original_chat' || preflight.kind === 'return_original_chat_direct_passthrough')",
      'const preflightKind = preflight.kind',
      'switch (preflightKind)',
      'invalid engine preflight result kind',
      'planServertoolEngineOrchestrationPreflightActionWithNative({',
      'switch (preflightOrchestrationAction.action)',
      'String(preflightOrchestrationAction.action)',
      'const preflightChat = (preflight as { chat?: JsonObject }).chat',
      'const preflightStopSignal = (preflight as { stopSignal?: typeof stopSignal }).stopSignal',
      'chat: preflightChat as JsonObject',
      'stopSignal = preflightStopSignal as typeof stopSignal',
      'hasServertoolCliProjectionContext:',
      'const engineSkipAction = engineSkipPlan.action as',
      'engineSkipPlan.skipReason as string',
      'switch (engineSkipPlan.action)',
      'const skipReason = engineSkipPlan.skipReason;',
      "engineSkipPlan.action === 'return_skipped_passthrough' ||",
      "engineSkipPlan.action === 'return_skipped_no_execution'",
      'if (stopSignal.observed) {',
      "engineResult.execution && typeof engineResult.execution === 'object'",
      "runtimeControl && typeof runtimeControl === 'object'",
      'engineResult.execution as unknown as Record<string, unknown>',
      'runtimeControl as Record<string, unknown>',
      'runtimeControl != null && typeof runtimeControl ===',
      'runtimeMetadataSnapshot?.metadataCenterSnapshot as Record<string, unknown>',
      'options.adapterContext as Record<string, unknown>',
      'options.adapterContext as unknown as Record<string, unknown>',
    ],
    required: [
      'resolveServertoolTimeoutMsFromEnvCandidatesWithNative({',
      'function resolveServerToolTimeoutMs()',
      'resolveServertoolEngineOrchestrationPreflightDecisionWithNative({',
      'chat: preflightDecision.chat',
      'stopSignal = preflightDecision.stopSignal',
      'resolveServertoolEngineSkipDecisionWithNative({',
      'skipReason: engineSkipDecision.skipReason',
      'result: engineSkipDecision.triggerResult',
      'return engineSkipDecision.shellResult',
      'const stoplessExecutionPlan = planStoplessExecutionWithNative({',
      'stoplessExecutionFlowId:',
      'const runtimeAction = planServertoolEngineRuntimeActionWithNative({',
      'planServertoolEngineTriggerObservationWithNative({',
      "engineResult.execution != null && typeof engineResult.execution === 'object'",
      'runtimeControl: runtimeControl ?? null',
      'engineResult: {',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-orchestration-shell.ts',
    forbidden: [
      'providerInvoker?:',
      'reenterPipeline?:',
      'clientInjectDispatch?:',
      'capabilities: {',
      'providerInvoker: options.providerInvoker',
      'reenterPipeline: options.reenterPipeline',
      'clientInjectDispatch: options.clientInjectDispatch',
      'const bypassResult: ServertoolResponseStageShellResult = {',
      'return bypassResult;',
      'const passthroughResult: ServertoolResponseStageShellResult = {',
      'return passthroughResult;',
      'options.adapterContext as Record<string, unknown>',
      'if (output.returnedExecutedPayload)',
      'payload: output.payload',
      'executed: output.executed',
    ],
    required: [
      'chat: options.payload',
      'adapterContext: options.adapterContext',
      'output.recordEvent',
      'extractServertoolResponseStageOrchestrationShellResultWithNative(output)',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/registry-orchestration-shell.ts',
    forbidden: [
      'isRegisteredServerToolNameViaNativeConfig',
      'isServertoolRegisteredNameByConfig',
      'type ServerToolHandlerRegistrationSpec',
      'export const listAutoServerToolHandlers',
      'getServerToolHandlerViaNativePlan',
      'export function listRegisteredServerToolHandlerNames(',
      'export function listRegisteredServerToolHandlerRecords(',
      'projectCurrentRegistrySources',
      'projectRegistrySources',
      'listBuiltinHandlerNames',
      'listBuiltinHandlerRecordEntries',
      "from './registry-projection-shell.js'",
      'projectAutoServerToolHookDescriptors',
      'export function isRegisteredServerToolName(',
      'resolveServertoolRegisteredNameWithNative',
      'export {\n  type ServerToolAutoHookDescriptor,',
      "if (actionPlan.action === 'return_builtin')",
      'registration: entry.registration as unknown as Record<string, unknown>',
      'execution: entry.execution as Record<string, unknown>',
      'const actionPlan = planServertoolRegistryLookupFromSkeletonWithNative({',
      'switch (actionPlan.action)',
      "case 'return_none':",
      'invalid registry lookup action',
      'name: actionPlan.canonicalName',
    ],
    required: [
      'resolveServertoolRegistryHandlerWithNative({',
      'planServertoolRegistryBuiltinAutoHookEntriesWithNative({',
    ],
  },
] as const;

function repoPath(relativePath: string): string {
  return path.join(process.cwd(), relativePath);
}

describe('servertool active orchestration audit', () => {
  for (const file of DELETED_FILES) {
    test(`${file} must stay physically deleted`, () => {
      expect(fs.existsSync(repoPath(file))).toBe(false);
    });
  }

  for (const target of TARGETS) {
    test(`${target.file} must not retain active orchestration owner markers`, () => {
      const source = fs.readFileSync(repoPath(target.file), 'utf8');
      const hits = target.forbidden.filter((marker) => source.includes(marker));
      expect(hits).toEqual([]);
      if (Array.isArray((target as { required?: string[] }).required)) {
        const misses = ((target as { required?: string[] }).required ?? []).filter(
          (marker) => !source.includes(marker)
        );
        expect(misses).toEqual([]);
      }
    });
  }
});
