import fs from 'node:fs';
import path from 'node:path';

const TARGETS = [
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-handler-materialization-shell.ts',
    forbidden: [
      'const SERVERTOOL_BACKEND_EXECUTORS',
      'const servertoolBackendExecutors',
      'const materializePlannedServertoolResult',
      'const executeBackendPlanViaThinShell',
      'const runServertoolHandlerThinShell',
      'function materializeServertoolPlannedResult(',
      'function executeServertoolBackendPlan(',
      'export async function runServertoolHandler(',
      '[servertool] invalid handler plan contract: missing finalize',
      '[servertool] invalid handler plan/result contract',
      '[servertool] handler failed:',
      '[servertool] vision_analysis backend requires reenterPipeline',
      '[servertool] unsupported backend plan kind:',
      "if (planHandlerMaterializationAction(planned, options) === 'handler_plan')",
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-dispatch-outcome-shell.ts',
    forbidden: [
      'const buildDispatchPlanInputViaThinShell',
      'const buildOutcomePlanInputViaThinShell',
      'const resolveToolCallExecutionOutcomeViaThinShell',
      'const runToolCallExecutionLoopViaThinShell',
      'const resolveHandlerExecutionSpecViaThinShell',
      'function buildServertoolDispatchPlanInputThinShell(',
      'function buildServertoolOutcomePlanInputThinShell(',
      'function resolveToolCallExecutionOutcomeThinShell(',
      'function runToolCallExecutionLoopThinShell(',
      'export function resolveServertoolHandlerExecutionSpec(',
      'args.appendToolOutput(',
      'JSON.stringify({',
      '[servertool] dispatch spec mismatch:',
      '[servertool] invalid native mixed-client-tools outcome contract',
      '[servertool] missing native followup contract for servertool-only outcome',
      "if (outcomePlan.outcomeMode === 'mixed_client_tools')",
      "outcomePlan.followupStrategy === 'reuse_last_execution'",
      '? args.executionState.lastExecution.followup',
      'args.executionState.lastExecution && args.executionState.executedToolCalls.length === 1',
      '${toolCall.name}_error',
      "if (!entry || entry.trigger !== 'tool_call')",
      'if (result) {',
      'if (lastErr) {',
      "executionMode: 'noop'",
      'stripAfterExecute: true',
      'noopResult.flowId',
      'noopResult.followup',
      'noopResult.executionContext',
      'executedToolCalls: [],',
      'executedIds: new Set<string>()',
      'executedFlowIds: []',
      'state.executedToolCalls.push({',
      'state.executedIds.add(toolCall.id)',
      'state.executedFlowIds.push(',
      'state.lastExecution = execution',
      'const newKeys = new Set(Object.keys(nextChatResponse));',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-shell.ts',
    forbidden: [
      'executedToolCalls: [],',
      'executedIds: new Set<string>()',
      'executedFlowIds: []',
      'state.executedToolCalls.push({',
      'state.executedIds.add(toolCall.id)',
      'state.executedFlowIds.push(',
      'state.lastExecution = execution',
      '[servertool] dispatch spec mismatch:',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/auto-hook-caller.ts',
    forbidden: [
      "result: 'error'",
      "reason: 'predicate_false'",
      "reason: 'matched_without_flow'",
      "reason: 'empty_materialized_result'",
      'if (!planned) {',
      'if (result) {',
      'if (optionalResult) {',
      'if (mandatoryResult) {',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/server-side-tools-impl.ts',
    forbidden: [
      "import './handlers/stop-message-auto.js';",
      "import './handlers/vision.js';",
      'export async function runServerSideToolEngineImpl(',
      'export function extractToolCallsImpl(',
      'export function collectAdditionalClientToolCallsImpl(',
      'if (!base) {',
      'if (isAdapterClientDisconnected(options.adapterContext)) {',
      "responseStagePlan?.nextAction === 'bypass'",
      'if (autoHookResult) {',
      'toolCall.id === preExecutionBranchPlan.projectedToolCallId',
      '[servertool] native execution-branch projected missing tool call id:',
      'hasServertoolSupport:',
      "typeof options.providerInvoker === 'function' || typeof options.reenterPipeline === 'function'",
        "'SERVERTOOL_CLIENT_DISCONNECTED'",
        "'[servertool] client disconnected before servertool execution'",
        '.find(isClientExecCliProjectionToolCall)',
        'executionState.executedToolCalls.length > 0',
        "executionMode === 'client_exec_cli_projection'",
        "flowId: 'servertool_cli_projection'",
        'servertoolCliProjection: {',
      "code: 'SERVERTOOL_STATE_LOAD_FAILED'",
      '[servertool] sticky routing state load failed:',
      'if (!persistentScopeKey) {',
      'asObject(directRuntime?.preCommandState) ??',
      'asObject((runtimeMetadata as Record<string, unknown> | undefined)?.preCommandState)',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/engine.ts',
    forbidden: [
      'function extractStoplessReasoningText(',
      'function extractStoplessLoopState(',
      'function readStoplessRouteName(',
      'function isDirectStoplessDisabled(',
      'const loopState = extractStoplessLoopState(',
      'reasoningText: extractStoplessReasoningText(',
      'const triggerHint = [',
      'const schemaFeedbackCandidate = [',
      'const repeatCount =',
      'const maxRepeats =',
      'extractCurrentAssistantStopTextWithNative(chatResponse ?? null) ||',
      'if (\n    containsSyntheticRouteCodexControlText(options.chat)\n  )',
      'if (stoplessIsDisabledOnDirectRoute(options.adapterContext))',
      "if (engineResult.mode === 'passthrough' || !engineResult.execution)",
      "!stoplessPlan.isStopMessageFlow &&",
      "if (stoplessPlan.action === 'terminal_final')",
      "if (stoplessPlan.action === 'cli_projection' && stoplessPlan.isStopMessageFlow)",
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/registry-impl.ts',
    forbidden: [
      'const toolHandlerRegistryImpl',
      'const autoHandlerRegistryImpl',
      'let autoHookOrderImpl = 0',
      'function resolveAutoHookPhaseRank(',
      '.sort((left, right) => {',
      'const phaseRankDiff =',
      'const priorityDiff =',
      'const orderDiff =',
      'if (builtinEntry) {',
      'return getAdHocHandlerEntry(canonicalName);',
      "phase: entry.autoHook?.phase ?? 'default'",
      "priority: entry.autoHook?.priority ?? 100",
      "order: entry.autoHook?.order ?? 0",
      'new Set([...listBuiltinHandlerNames(), ...listAdHocHandlerNames()])',
      '.sort()',
      'return [...listBuiltinAutoHandlerEntries(), ...listAdHocAutoHandlerEntries()]',
      "entry.registration.trigger === 'tool_call'",
      "entry.registration.trigger === 'auto'",
      'export function registerServerToolHandlerImpl(',
      'export function getServerToolHandlerImpl(',
      'export function listAutoHandlersForRegistryImpl(',
      'export function collectAutoServerToolHooksImpl(',
    ],
  },
] as const;

function repoPath(relativePath: string): string {
  return path.join(process.cwd(), relativePath);
}

describe('servertool active orchestration audit', () => {
  for (const target of TARGETS) {
    test(`${target.file} must not retain active orchestration owner markers`, () => {
      const source = fs.readFileSync(repoPath(target.file), 'utf8');
      const hits = target.forbidden.filter((marker) => source.includes(marker));
      expect(hits).toEqual([]);
    });
  }
});
