import fs from 'node:fs';
import path from 'node:path';

const DELETED_FILES = [
  'sharedmodule/llmswitch-core/src/servertool/execution-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/execution-dispatch-outcome-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry-impl.ts',
  'sharedmodule/llmswitch-core/src/servertool/adhoc-handler-test-support.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry-registration-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry-projection-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/registry-types.ts',
  'sharedmodule/llmswitch-core/src/servertool/builtin-handler-catalog.ts',
  'sharedmodule/llmswitch-core/src/servertool/pre-command-hooks.ts',
  'sharedmodule/llmswitch-core/src/servertool/pre-command-runtime-state-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/pending-session.ts',
  'sharedmodule/llmswitch-core/src/servertool/pending-injection-block.ts',
  'sharedmodule/llmswitch-core/src/servertool/skeleton-config.ts',
  'sharedmodule/llmswitch-core/src/servertool/orchestration-policy-block.ts',
  'sharedmodule/llmswitch-core/src/servertool/cli-projection-runtime-shell.ts',
  'sharedmodule/llmswitch-core/src/servertool/engine.ts',
  'tests/servertool/cli-projection-runtime-shell.spec.ts',
  'sharedmodule/llmswitch-core/rust-core/crates/servertool-core/src/pre_command_hook_contract.rs',
  'sharedmodule/llmswitch-core/rust-core/crates/servertool-core/src/pending_session_contract.rs',
] as const;

const TARGETS = [
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/types.ts',
    forbidden: [
      'providerProtocol: string;\n  disableToolCallHandlers?: boolean;',
      'providerProtocol: string;\n  runtimeMetadata?: JsonObject;',
    ],
    required: [
      'export interface ServerSideToolEngineOptions',
      'export interface ServerToolHandlerContext',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-handler-materialization-shell.ts',
    forbidden: [
      'const SERVERTOOL_BACKEND_EXECUTORS',
      'const servertoolBackendExecutors',
      'const materializePlannedServertoolResult',
      'function dehydrateExecutionLoopState(',
      'function hydrateExecutionLoopState(',
      'createServertoolExecutionLoopStateFromNative',
      'appendExecutedToolRecordFromNative',
      'new Set(state.executedIds)',
      'const executeBackendPlanViaThinShell',
      'const runServertoolHandlerThinShell',
      'export async function executeBuiltinServerToolHandler(',
      'function materializeServertoolPlannedResult(',
      'export async function runServertoolHandler(',
      '[servertool] invalid handler plan contract: missing finalize',
      '[servertool] invalid handler plan/result contract',
      '[servertool] handler failed:',
      'buildHandlerRuntimeActionInput',
      'buildProviderProtocolError',
      'function throwServertoolExecutionDispatchError(',
      'planServertoolExecutionDispatchErrorWithNative(args)',
      'planServertoolExecutionDispatchErrorWithNative({',
      'planServertoolHandlerContractErrorWithNative(',
      "actionPlan.action === 'invalid_plan_missing_finalize'",
      "actionPlan.action === 'invalid_plan_result'",
      "if (actionPlan.action === 'finalize_without_backend')",
      "if (actionPlan.action === 'throw_handler_error')",
      "outcomeRuntimeActionPlan.action === 'invalid_mixed_client_tools_outcome'",
      "outcomeRuntimeActionPlan.action === 'missing_servertool_execution_contract'",
      "import { ProviderProtocolError }",
      'planServertoolHandlerRuntimeActionWithNative(',
      '[servertool] vision_analysis backend requires reenterPipeline',
      '[servertool] unsupported backend plan kind:',
      "if (planHandlerMaterializationAction(planned, options) === 'handler_plan')",
      'structuredClone(args.base)',
    ],
    required: [
      'throw createServertoolProviderProtocolErrorFromPlan(',
      'planServertoolExecutionOutcomeMaterializationWithNative({',
      'planServertoolHandlerMaterializationForPlannedWithNative(',
      'switch (actionPlan.action)',
      'const outcomePlan = planServertoolOutcomeWithNative(',
      'buildServertoolOutcomePlanInputWithNative({',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-queue-shell.ts',
    forbidden: [
      '  ToolCall\n} from \'./types.js\';',
      "String(lastErr ?? 'unknown')",
      "lastErr instanceof Error ? lastErr.message : String",
      'lastErr instanceof Error ? lastErr.message : lastErr',
      'Boolean(lastErr)',
      'Boolean(entry)',
      'Boolean(result)',
      'planned ? await materializeServertoolPlannedResult',
    ],
    required: [
      'runServertoolIoExecutionQueue',
      'planServertoolExecutionLoopRuntimeActionWithNative',
      'createServertoolExecutionLoopStateWithNative',
      'appendServertoolExecutedRecordWithNative',
      'createServertoolProviderProtocolErrorFromPlan',
      'hasHandlerEntry: entry != null',
      'planned != null ? await materializeServertoolPlannedResult',
      'hasMaterializedResult: result != null',
      'message: errorEffectPlan.handlerErrorMessage as string',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/orchestration-blocks.ts',
    forbidden: [
      'export function appendToolOutput(',
      "nativeRecord({ op: 'append_tool_output'",
      'export function buildAssistantToolCallMessage(',
      'export function buildToolMessagesFromOutputs(',
      'export function stripToolOutputs(',
      'export function patchToolCallArgumentsById(',
      'export function filterOutExecutedToolCalls(',
      'export function buildAutoHookQueuesFromConfig(',
      'planServertoolAutoHookQueuesWithNative',
      'sourceIndex',
      'function replaceJsonObjectInPlaceInternal(',
      'function nativeArray(',
      'function nativeRecord(',
      '.filter((hook): hook is',
      '.filter(Boolean)',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/timeout-error-block.ts',
    forbidden: [
      'export function createServerToolTimeoutError(',
      'export function createServertoolRequiredResponseHookEmptyError(',
      'export function createServerToolClientDisconnectedError(',
    ],
    required: [
      'export function createServertoolProviderProtocolErrorFromPlan(',
      'planServertoolTimeoutWatcherWithNative',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/auto-hook-caller.ts',
    forbidden: [
      "outcome: 'error'",
      "outcome: 'planned_null'",
      "outcome: 'materialized_match'",
      "outcome: 'materialized_empty'",
      "result: 'error'",
      "reason: 'predicate_false'",
      "reason: 'matched_without_flow'",
      "reason: 'empty_materialized_result'",
      'errorAttemptInput',
      'runtimeAttemptInput',
      'callerFinalizationInput',
      'if (!planned) {',
      'if (result) {',
      'if (!result)',
      'if (!queueResult)',
      'native auto-hook execution requested result but materialization was empty',
      'native auto-hook queue progress requested result but queue result was empty',
      'native auto-hook execution returned no materialized disposition',
      'if (optionalResult) {',
      'result.execution.flowId.trim()',
      'if (mandatoryResult) {',
      'const toolFlowResult: ServerSideToolEngineResult = {',
      'return toolFlowResult;',
      'export async function runAutoHookExecutionQueue(',
      'ServerToolHandlerPlan',
      'function planAutoHookRuntimeAttempt(',
      'const attemptPlan = planAutoHookRuntimeAttempt({',
      'function planAutoHookCallerFinalization(',
      'const finalizationPlan = planAutoHookCallerFinalization({',
      'if (finalizationPlan.returnResult)',
      'if (finalizationPlan.continueNextQueue)',
      'if (finalizationPlan.returnNull)',
      'const finalQueueName = queueOrder[queueOrder.length - 1]?.queueName;',
      'const finalQueue = queue.queueName === finalQueueName;',
      'finalQueue',
      "String(error ?? 'unknown')",
      'error instanceof Error ? error.message : String',
      "typeof error === 'string' ? error",
      'planServertoolAutoHookQueuesWithNative({',
      'args.hooks[entry.sourceIndex]',
      'native auto-hook queue returned invalid sourceIndex',
    ],
    required: [
      'const attemptPlan = planAutoHookRuntimeAttemptWithNative({',
      'planServertoolAutoHookQueueItemsWithNative({',
      'const finalizationPlan = planAutoHookCallerFinalizationWithNative({',
      'switch (finalizationPlan.action)',
      'queueIndex: queueIndex + 1',
      'queueTotal: queueOrder.length',
      "mode: 'tool_flow'",
      'const queueResultForReturn = queueResult as ServerToolHandlerResult',
      'finalChatResponse: queueResultForReturn.chatResponse',
      'execution: queueResultForReturn.execution',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-finalize-shell.ts',
    forbidden: [
      "const passthroughResult = { mode: 'passthrough', finalChatResponse: args.baseObject } as const;",
      'return passthroughResult;',
      'initialResponseStageGatePlan',
      'planServertoolResponseStageGateWithNative',
      'readRuntimeControlFromAnyBoundMetadataCenter',
      'responseHookMatched === true',
      "responseStageAutoHook.action === 'return_passthrough_bypass'",
      "responseStageAutoHook.action === 'return_auto_hook_result'",
      "if (finalizeRuntimeAction.action === 'return_auto_hook_result')",
    ],
    required: [
      'runServertoolResponseStageAutoHookPass',
      'responseStageGatePlan: args.responseStageGatePlan',
      'planServertoolResponseStageRuntimeActionWithNative',
      'switch (finalizeRuntimeAction.action)',
      'hasAutoHookResult: autoHookResult != null',
      "return { mode: 'passthrough', finalChatResponse: args.baseObject };",
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-auto-hook-shell.ts',
    forbidden: [
      "if (preAutoHookRuntimeAction.action === 'return_passthrough_bypass')",
      "if (postAutoHookRuntimeAction.action === 'return_required_response_hook_empty')",
      "if (postAutoHookRuntimeAction.action === 'return_auto_hook_result')",
    ],
    required: [
      'switch (preAutoHookRuntimeAction.action)',
      'switch (postAutoHookRuntimeAction.action)',
      'result: autoHookResult as ServerSideToolEngineResult',
      'responseHookName: postAutoHookRuntimeAction.responseHookName as string',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-prepass-shell.ts',
    forbidden: [
      'responseHookMatched !== true',
      'responseStageGatePlan.responseHookMatched !== true',
      "prepassRuntimeAction.action !== 'run_auto_hooks'",
      "if (responseStageAutoHook.action === 'return_auto_hook_result')",
    ],
    required: [
      'planServertoolResponseStageGateWithNative',
      'planServertoolResponseStageRuntimeActionWithNative',
      'switch (prepassRuntimeAction.action)',
      'switch (responseStageAutoHook.action)',
      'runServertoolResponseStageAutoHookPass',
      "action: 'continue_to_execution' as const",
      'responseStageGatePlan',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/extract-tool-calls-shell.ts',
    forbidden: [
      'function asObject(',
    ],
    required: [
      'runServertoolResponseStageWithNative',
      'replaceJsonObjectInPlace',
      'stage.toolCalls.map(',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/dispatch-preparation-shell.ts',
    forbidden: [
      "from '../conversion/runtime-metadata.js'",
      'readRuntimeMetadata(',
      'resolveServertoolRuntimePreCommandState',
      'applyPreCommandHooksToToolCalls',
      'buildServertoolDispatchPlanInput(',
      '...(args.includeToolCallNames ? { includeToolCallHandlerNames: [...args.includeToolCallNames] } : {})',
      '...(args.excludeToolCallNames ? { excludeToolCallHandlerNames: [...args.excludeToolCallNames] } : {})',
      'baseObject: JsonObject;',
      'baseForExecution: JsonObject;',
      'readProviderProtocolFromAnyBoundMetadataCenter',
      'Servertool dispatch preparation requires metadata center runtime_control.providerProtocol',
    ],
    required: [
      'readRuntimeMetadataSnapshotFromAnyBoundMetadataCenter',
      'planServertoolToolCallDispatchWithNative',
      'buildServertoolDispatchPlanInputWithNative',
      'dispatchPlan: planServertoolToolCallDispatchWithNative(',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/entry-preflight-shell.ts',
    forbidden: [
      'createServerToolClientDisconnectedError',
      "if (entryPreflightPlan.action === 'return_passthrough_non_object_chat')",
      "if (entryPreflightPlan.action === 'throw_client_disconnected')",
    ],
    required: [
      'planServertoolEntryPreflightWithNative',
      'planServertoolClientDisconnectedErrorWithNative',
      'createServertoolProviderProtocolErrorFromPlan',
      'switch (entryPreflightPlan.action)',
      "result: { mode: 'passthrough', finalChatResponse: args.options.chatResponse }",
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/engine-preflight-shell.ts',
    forbidden: [
      'stopSignal.observed && preflightAction.action',
      'if (stopSignal.observed) {',
      "if (preflightAction.action === 'return_original_chat')",
      "if (preflightAction.action === 'return_original_chat_direct_passthrough')",
    ],
    required: [
      'runEnginePreflight',
      'planServertoolEnginePreflightWithNative',
      'inspectStopGatewaySignal(',
      'attachStopGatewayContext(',
      'containsSyntheticRouteCodexControlTextWithNative(',
      "case 'return_original_chat'",
      "case 'return_original_chat_direct_passthrough'",
      "case 'continue_to_engine'",
      'preflightAction.attachStopGatewayContext === true',
      'preflightAction.logStopEntry',
      'preflightAction.logStopCompare',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/entry-context-shell.ts',
    forbidden: [
      'export function asServertoolJsonObject(',
      'readProviderProtocolFromAnyBoundMetadataCenter',
      'Servertool entry context requires metadata center runtime_control.providerProtocol',
      'entryContextPlan.includeToolCallNames.length > 0',
      'entryContextPlan.excludeToolCallNames.length > 0',
      'entryContextPlan.includeAutoHookIds.length > 0',
      'entryContextPlan.excludeAutoHookIds.length > 0',
    ],
    required: [
      'resolveServertoolEntryContext',
      'planServertoolEntryContextWithNative',
      'const includeToolCallNames =',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/engine-selection-block.ts',
    forbidden: [
      'primaryAutoHookIds.length',
      'engineResult.mode',
      '!engineResult.execution',
      "mode === 'passthrough'",
      'function toEngineOverrides(',
      'planServertoolSkeletonDerivedConfigWithNative',
      'autoHookQueueConfig as',
      'optionalPrimaryOrder: string[]',
      'primaryAutoHookAttempt:',
      'disableToolCallHandlers: true',
      'includeAutoHookIds: primaryAutoHookIds',
      'excludeAutoHookIds: primaryAutoHookIds',
      'typeof startPlan.overrides.disableToolCallHandlers',
      'Array.isArray(startPlan.overrides.includeAutoHookIds)',
      'Array.isArray(startPlan.overrides.excludeAutoHookIds)',
      'typeof overrides.disableToolCallHandlers',
      'Array.isArray(overrides.includeAutoHookIds)',
      'Array.isArray(overrides.excludeAutoHookIds)',
    ],
    required: [
      'readServertoolPrimaryAutoHookIdsWithNative',
      'planEngineSelectionStartWithNative',
      'planEngineSelectionAfterRunWithNative',
      'const engineResult = await args.runEngine(startPlan.overrides);',
      'return await args.runEngine(afterRunPlan.overrides ?? {});',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/run-server-side-tool-engine-shell.ts',
    forbidden: [
      "const passthroughResult = { mode: 'passthrough', finalChatResponse: options.chatResponse } as const;",
      "import type { JsonObject } from '../conversion/hub/types/json.js';",
    ],
    required: [
      'orchestrateServertoolEngine',
      'runServertoolEntryPreflight',
      'extractToolCallsFromResponseStage',
      'resolveServertoolEntryContext',
      'runServertoolResponseStagePrePass',
      'runServertoolExecutionStage',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-stage-shell.ts',
    forbidden: [
      'structuredClone(args.baseObject)',
      'const baseForExecution = structuredClone',
      'const baseForExecution = args.baseObject;',
      'isStopMessageAutoPreProjection',
      'filterOutExecutedToolCalls',
      'stripToolOutputs',
      'function planExecutionBranchRuntimeAction(',
      'const preExecutionBranchPlan = planExecutionBranchRuntimeAction({',
      'const postExecutionBranchPlan = planExecutionBranchRuntimeAction({',
      "if (preExecutionBranchPlan.action === 'client_exec_cli_projection')",
      "if (postExecutionBranchPlan.action === 'resolve_execution_outcome')",
      'if (!projectedToolCall)',
      'native execution-branch projected missing tool call',
    ],
    required: [
      'prepareServertoolDispatchStage',
      'planServertoolExecutionBranchWithNative',
      'const preExecutionBranchPlan = planServertoolExecutionBranchWithNative({',
      'const postExecutionBranchPlan = planServertoolExecutionBranchWithNative({',
      'runServertoolIoExecutionQueue',
      'materializeNativeToolCallExecutionOutcome',
      'finalizeServertoolResponseStage',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-orchestration-shell.ts',
    forbidden: [
      "from './server-side-tools-impl.js'",
      'runServertoolResponseStageWithNative',
      'const responseStage =',
      'readFollowupClientInjectSourceWithNative',
      'writeRuntimeControlToBoundMetadataCenter(',
      'servertoolResponseOrchestration',
      'providerProtocol: ProviderProtocol;',
      'const providerProtocol =',
      'Servertool response stage orchestration requires metadata center runtime_control.providerProtocol',
      'function planServertoolResponseStageGate(',
      'const gatePlan = planServertoolResponseStageGate({',
      "gatePlan.skipReason || 'followup_bypass'",
      "gatePlan.skipReason === 'no_servertool_support'",
      "gatePlan.skipReason === 'followup_bypass'",
      "throw new Error('[servertool] native response-stage gate bypass missing skipReason')",
      'typeof gatePlan.skipReason',
      'gatePlan.skipReason.trim()',
      "gatePlan.nextAction === 'bypass'",
      "if (gateRuntimeAction.action === 'return_passthrough_bypass')",
      'if (orchestration.executed)',
    ],
    required: [
      'const gatePlan = planServertoolResponseStageGateWithNative({',
      'planServertoolResponseStageRuntimeActionWithNative',
      'switch (gateRuntimeAction.action)',
      "case 'return_passthrough_bypass'",
      'detectProviderResponseShapeWithNative',
      'const orchestration = await runServerToolOrchestrationShell(',
      'runServerToolOrchestrationShell',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/execution-stage-shell.ts',
    forbidden: [
      "from './cli-projection-runtime-shell.js'",
      'buildServertoolCliProjectionBranchResult',
      'toolCall.id === preExecutionBranchPlan.projectedToolCallId',
      'preExecutionBranchPlan.projectedToolCallIndex',
      'dispatchPlan.executableToolCalls[preExecutionBranchPlan.projectedToolCallIndex]',
      'if (!projectedToolCall)',
      'native execution-branch projected missing tool call',
      '.find(isClientExecCliProjectionToolCall)',
      'export function isClientExecCliProjectionToolCall(',
      'export const collectAdditionalClientToolCalls',
      'function parseToolArguments(',
      'JSON.parse(value)',
      'const projectionShellInput = {',
      'buildClientVisibleProjectionShellWithNative(projectionShellInput)',
      'function buildClientVisibleProjectionShellForRuntime(',
      'const projectionInput = parseServertoolCliProjectionToolArgumentsWithNative({',
      'input: parseServertoolCliProjectionToolArgumentsWithNative({',
      'input: projectionInput',
      'const nativeProjection = buildClientExecCliProjectionOutputWithNative({',
      'buildClientExecCliProjectionOutputWithNative',
      'const chatResponse = buildClientVisibleProjectionShellWithNative({',
      'buildClientVisibleProjectionShellWithNative',
      'const execution = buildServertoolCliProjectionExecutionContextWithNative({',
      'buildServertoolCliProjectionExecutionContextWithNative',
      'randomUUID',
      'servertool_cli_projection',
      'reasoningText',
      '继续执行本地 hook',
    ],
    required: [
      'buildServertoolCliProjectionRuntimeBranchWithNative({',
      'const projectedToolCall = preExecutionBranchPlan.projectedToolCall',
      'finalChatResponse: branch.chatResponse as JsonObject',
      'execution: branch.execution as {',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/engine-postflight-shell.ts',
    forbidden: [
      'function applyServertoolPostflightMetadataWritePlan(',
      'function buildStoplessProjectionMetadataCenterSnapshot(',
      'function printServertoolLine(',
      "symbol: 'applyServertoolPostflightMetadataWritePlan'",
      'const followupSummary: Record<string, unknown> = {',
      "if ('payload' in followup)",
      'payloadRecord.messages',
      'payloadRecord.input',
      "if ('injection' in followup)",
      'followup.injection?.ops',
      'const engineFinalResult = {',
      'return engineFinalResult;',
      'const requestTruth = metadataCenterSnapshot?.requestTruth',
      'const rawSessionId = requestTruth?.sessionId',
      'rawSessionId.trim()',
      "if (runtimeAction.action === 'return_servertool_cli_projection_final')",
      "if (runtimeAction.action === 'return_stop_message_terminal_final')",
      "if (runtimeAction.action === 'build_stop_message_cli_projection')",
    ],
    required: [
      'switch (runtimeAction.action)',
      'buildServertoolPostflightObservationSummaryWithNative({',
      "args.stageRecorder.record('servertool.execution', summary);",
      'chat: engineResult.finalChatResponse',
      'executed: true',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/progress-log-block.ts',
    forbidden: [
      'function resolveStage(',
      'function normalizeResult(',
      'event.reason.trim().toLowerCase().replace',
      'compareContext.reason.toLowerCase().replace',
      'extra.flowId.trim()',
      'flowId.trim()',
    ],
    required: [
      'normalizeServertoolProgressFlowIdWithNative({ value: extra?.flowId })',
      'normalizeServertoolProgressFlowIdWithNative({ value: flowId })',
      'resolveServertoolProgressStageWithNative({ step, message })',
      'normalizeServertoolProgressResultWithNative({ message })',
      'normalizeServertoolProgressTokenWithNative({ value: event.reason })',
      'normalizeServertoolProgressTokenWithNative({ value: compareContext.reason })',
      'export function appendServertoolMatchSkippedProgressEvent(',
      'readProviderProtocolFromAnyBoundMetadataCenter(args.adapterContext',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/engine-orchestration-shell.ts',
    forbidden: [
      'const stoplessExecutionInput = {',
      'const hasServertoolCliProjectionContext =',
      'function planStoplessEngineRuntime(',
      'const { stoplessExecution, runtimeAction } = planStoplessEngineRuntime({',
      'planStoplessExecutionWithNative(stoplessExecutionInput)',
      'const postflightEngineResult = {',
      'engineResult: postflightEngineResult,',
      'function createServerToolEngineRunner(',
      'type ServerToolEngineRunner =',
      "from './orchestration-policy-block.js'",
      'readProviderProtocolFromAnyBoundMetadataCenter',
      'providerProtocol: args.providerProtocol',
      'Servertool engine orchestration requires metadata center runtime_control.providerProtocol',
      'parseServertoolTimeoutMsWithNative({ raw: raw || undefined })',
      '.map((key) => process.env[key]).find((value) => Boolean(value))',
    ],
    required: [
      'resolveServertoolTimeoutMsFromEnvCandidatesWithNative({',
      'function resolveServerToolTimeoutMs()',
      'const stoplessExecutionPlan = planStoplessExecutionWithNative({',
      'const runtimeAction = planServertoolEngineRuntimeActionWithNative({',
      'engineResult: {',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/response-stage-orchestration-shell.ts',
    forbidden: [
      'providerInvoker?:',
      'reenterPipeline?:',
      'clientInjectDispatch?:',
      'capabilities: {',
      'providerInvoker: options.providerInvoker',
      'reenterPipeline: options.reenterPipeline',
      'clientInjectDispatch: options.clientInjectDispatch',
      'const bypassResult: ServertoolResponseStageShellResult = {',
      'return bypassResult;',
      'const passthroughResult: ServertoolResponseStageShellResult = {',
      'return passthroughResult;',
    ],
    required: [
      "return {",
      'payload: options.payload',
      'executed: false',
    ],
  },
  {
    file: 'sharedmodule/llmswitch-core/src/servertool/registry-orchestration-shell.ts',
    forbidden: [
      'isRegisteredServerToolNameViaNativeConfig',
      'isServertoolRegisteredNameByConfig',
      'type ServerToolHandlerRegistrationSpec',
      'export const listAutoServerToolHandlers',
      'getServerToolHandlerViaNativePlan',
      'export function listRegisteredServerToolHandlerNames(',
      'export function listRegisteredServerToolHandlerRecords(',
      'projectCurrentRegistrySources',
      'projectRegistrySources',
      'listBuiltinHandlerNames',
      'listBuiltinHandlerRecordEntries',
      "from './registry-projection-shell.js'",
      'projectAutoServerToolHookDescriptors',
      'export function isRegisteredServerToolName(',
      'resolveServertoolRegisteredNameWithNative',
      'export {\n  type ServerToolAutoHookDescriptor,',
      "if (actionPlan.action === 'return_builtin')",
    ],
    required: [
      'const actionPlan = planServertoolRegistryLookupFromSkeletonWithNative({',
      'switch (actionPlan.action)',
      'planServertoolRegistryBuiltinAutoHookEntriesWithNative({',
    ],
  },
] as const;

function repoPath(relativePath: string): string {
  return path.join(process.cwd(), relativePath);
}

describe('servertool active orchestration audit', () => {
  for (const file of DELETED_FILES) {
    test(`${file} must stay physically deleted`, () => {
      expect(fs.existsSync(repoPath(file))).toBe(false);
    });
  }

  for (const target of TARGETS) {
    test(`${target.file} must not retain active orchestration owner markers`, () => {
      const source = fs.readFileSync(repoPath(target.file), 'utf8');
      const hits = target.forbidden.filter((marker) => source.includes(marker));
      expect(hits).toEqual([]);
      if (Array.isArray((target as { required?: string[] }).required)) {
        const misses = ((target as { required?: string[] }).required ?? []).filter(
          (marker) => !source.includes(marker)
        );
        expect(misses).toEqual([]);
      }
    });
  }
});
