export declare const RCC_SUBDIRS: {
    readonly auth: "auth";
    readonly tokens: "tokens";
    readonly quota: "quota";
    readonly state: "state";
    readonly logs: "logs";
    readonly sessions: "sessions";
    readonly snapshots: "codex-samples";
    readonly provider: "provider";
    readonly config: "config";
    readonly guardian: "guardian";
    readonly login: "login";
    readonly statics: "statics";
    readonly errorsamples: "errorsamples";
    readonly llmsShadow: "llms-shadow";
    readonly camoufoxFingerprint: "camoufox-fp";
    readonly camoufoxProfiles: "camoufox-profiles";
    readonly docs: "docs";
    readonly precommand: "precommand";
    readonly runtimeLifecycle: "state/runtime-lifecycle";
    readonly run: "run";
    readonly tokenStats: "state/token-manager";
};
export type RccSubdirKey = keyof typeof RCC_SUBDIRS;
export declare function resolveRccUserDir(homeDir?: string): string;
export declare function resolveLegacyRouteCodexUserDir(homeDir?: string): string;
export declare function resolveRccUserDirForRead(homeDir?: string): string;
export declare function resolveRccPath(...segments: string[]): string;
export declare function resolveLegacyRouteCodexPath(...segments: string[]): string;
export declare function resolveRccPathForRead(...segments: string[]): string;
export declare function resolveRccSubdir(key: RccSubdirKey, homeDir?: string): string;
export declare function resolveRccSubdirForRead(key: RccSubdirKey, homeDir?: string): string;
export declare function resolveRccAuthDir(homeDir?: string): string;
export declare function resolveRccAuthDirForRead(homeDir?: string): string;
export declare function resolveRccTokensDir(homeDir?: string): string;
export declare function resolveRccTokensDirForRead(homeDir?: string): string;
export declare function resolveRccQuotaDir(homeDir?: string): string;
export declare function resolveRccQuotaDirForRead(homeDir?: string): string;
export declare function resolveRccStateDir(homeDir?: string): string;
export declare function resolveRccStateDirForRead(homeDir?: string): string;
export declare function resolveRccLogsDir(homeDir?: string): string;
export declare function resolveRccLogsDirForRead(homeDir?: string): string;
export declare function resolveRccSessionsDir(homeDir?: string): string;
export declare function resolveRccSessionsDirForRead(homeDir?: string): string;
export declare function resolveRccSnapshotsDir(homeDir?: string): string;
export declare function resolveRccSnapshotsDirFromEnv(homeDir?: string): string;
export declare function resolveRccSnapshotsDirForRead(homeDir?: string): string;
export declare function resolveRccProviderDir(homeDir?: string): string;
export declare function resolveRccProviderDirForRead(homeDir?: string): string;
export declare function resolveRccConfigDir(homeDir?: string): string;
export declare function resolveRccConfigDirForRead(homeDir?: string): string;
export declare function resolveRccGuardianDir(homeDir?: string): string;
export declare function resolveRccLoginDir(homeDir?: string): string;
export declare function resolveRccStaticsDir(homeDir?: string): string;
export declare function resolveRccErrorsamplesDir(homeDir?: string): string;
export declare function resolveRccLlmsShadowDir(homeDir?: string): string;
export declare function resolveRccCamoufoxFingerprintDir(homeDir?: string): string;
export declare function resolveRccCamoufoxProfilesDir(homeDir?: string): string;
export declare function resolveRccDocsDir(homeDir?: string): string;
export declare function resolveRccPrecommandDir(homeDir?: string): string;
export declare function resolveRccRuntimeLifecycleDir(homeDir?: string): string;
export declare function resolveRccRunDir(homeDir?: string): string;
export declare function resolveRccTokenStatsDir(homeDir?: string): string;
export declare function ensureRccUserDirEnvironment(homeDir?: string): string;
