/**
 * /v1/responses SSE-side handler bridge surface.
 *
 * Dedicated SSE projection-facing facade for responses SSE/JSON streaming
 * behaviors. Lifecycle persistence stays in responses-response-bridge.ts.
 */

// feature_id: server.responses_sse_bridge_surface
// canonical_builders: hasResponsesSsePayloadForHttp, shouldDispatchResponsesSseToClientForHttp, resolveResponsesRequestContextForHttp, assertDirectPassthroughResponsesSseMetadataIsolationForHttp, updateResponsesContractProbeFromSseChunkForHttp, inspectResponsesTerminalStateFromSseChunkForHttp, summarizeResponsesSseFrameForLogForHttp, resolveResponsesProviderProtocolHintFromSseFrameForHttp, buildResponsesTerminalSseFramesFromProbeForHttp, isToolCallContinuationResponseForHttp, inspectResponsesContinuationProbeForHttp, planResponsesContinuationCloseActionForHttp, shouldRepairResponsesContinuationTerminalForHttp, planResponsesStreamEndRepairForHttp, buildResponsesSseErrorPayloadForHttp, buildResponsesStructuredSseErrorPayloadForHttp, buildResponsesMissingSseBridgeErrorPayloadForHttp, buildResponsesStreamIncompleteErrorPayloadForHttp, createResponsesJsonToSseConverterForHttp, prepareResponsesJsonBodyForSseBridgeForHttp, normalizeResponsesJsonBodyForHttp, buildResponsesPayloadFromChatForHttp, projectResponsesClientPayloadForClientForHttp, projectResponsesSseFrameForClientForHttp, normalizeResponsesSseFrameForClientForHttp

import type { ResponsesRequestContextForHttp } from './responses-response-bridge.js';
import {
  assertDirectPassthroughResponsesSseFrameForHttp as assertDirectPassthroughResponsesSseFrameForHttpImpl,
  assertDirectPassthroughResponsesSseMetadataIsolationForHttp as assertDirectPassthroughResponsesSseMetadataIsolationForHttpImpl,
  buildClientSseKeepaliveFrameForHttp as buildClientSseKeepaliveFrameForHttpImpl,
  buildResponsesMissingSseBridgeErrorPayloadForHttp as buildResponsesMissingSseBridgeErrorPayloadForHttpImpl,
  buildResponsesPayloadFromChatForHttp as buildResponsesPayloadFromChatForHttpImpl,
  buildResponsesRequestLogContextForHttp as buildResponsesRequestLogContextForHttpImpl,
  buildResponsesSseErrorPayloadForHttp as buildResponsesSseErrorPayloadForHttpImpl,
  buildResponsesStreamIncompleteErrorPayloadForHttp as buildResponsesStreamIncompleteErrorPayloadForHttpImpl,
  buildResponsesStructuredSseErrorPayloadForHttp as buildResponsesStructuredSseErrorPayloadForHttpImpl,
  buildResponsesTerminalSseFramesFromProbeForHttp as buildResponsesTerminalSseFramesFromProbeForHttpImpl,
  createResponsesJsonToSseConverterForHttp as createResponsesJsonToSseConverterForHttpImpl,
  hasResponsesSsePayloadForHttp as hasResponsesSsePayloadForHttpImpl,
  importResponsesHandlerCoreDist as importResponsesHandlerCoreDistImpl,
  inspectResponsesContinuationProbeForHttp as inspectResponsesContinuationProbeForHttpImpl,
  inspectResponsesTerminalStateFromSseChunkForHttp as inspectResponsesTerminalStateFromSseChunkForHttpImpl,
  isDirectPassthroughTransportKeepaliveFrameForHttp as isDirectPassthroughTransportKeepaliveFrameForHttpImpl,
  isToolCallContinuationResponseForHttp as isToolCallContinuationResponseForHttpImpl,
  normalizeChatUsagePayloadForHttp as normalizeChatUsagePayloadForHttpImpl,
  normalizeResponsesClientPayloadForHttp as normalizeResponsesClientPayloadForHttpImpl,
  normalizeResponsesJsonBodyForHttp as normalizeResponsesJsonBodyForHttpImpl,
  normalizeResponsesSseFrameForClientForHttp as normalizeResponsesSseFrameForClientForHttpImpl,
  planResponsesContinuationCloseActionForHttp as planResponsesContinuationCloseActionForHttpImpl,
  planResponsesStreamEndRepairForHttp as planResponsesStreamEndRepairForHttpImpl,
  prepareResponsesJsonBodyForSseBridgeForHttp as prepareResponsesJsonBodyForSseBridgeForHttpImpl,
  prepareResponsesJsonClientDispatchPlanForHttp as prepareResponsesJsonClientDispatchPlanForHttpImpl,
  prepareResponsesJsonSseDispatchPlanForHttp as prepareResponsesJsonSseDispatchPlanForHttpImpl,
  projectResponsesClientPayloadForClientForHttp as projectResponsesClientPayloadForClientForHttpImpl,
  projectResponsesSseFrameForClientForHttp as projectResponsesSseFrameForClientForHttpImpl,
  requireResponsesHandlerCoreDist as requireResponsesHandlerCoreDistImpl,
  resolveResponsesClientPayloadFinishReasonForHttp as resolveResponsesClientPayloadFinishReasonForHttpImpl,
  resolveResponsesProviderProtocolHintFromSseFrameForHttp as resolveResponsesProviderProtocolHintFromSseFrameForHttpImpl,
  resolveResponsesRequestContextForHttp as resolveResponsesRequestContextForHttpImpl,
  resolveResponsesTerminalProbeFinishReasonForHttp as resolveResponsesTerminalProbeFinishReasonForHttpImpl,
  shouldDispatchResponsesSseToClientForHttp as shouldDispatchResponsesSseToClientForHttpImpl,
  shouldDropClientSseFrameForHttp as shouldDropClientSseFrameForHttpImpl,
  shouldPersistResponsesContinuationOnProbeUpdateForHttp as shouldPersistResponsesContinuationOnProbeUpdateForHttpImpl,
  shouldPersistResponsesConversationStateForHttp as shouldPersistResponsesConversationStateForHttpImpl,
  shouldRepairResponsesContinuationTerminalForHttp as shouldRepairResponsesContinuationTerminalForHttpImpl,
  shouldRequireResponsesTerminalEventForHttp as shouldRequireResponsesTerminalEventForHttpImpl,
  summarizeResponsesSseFrameForLogForHttp as summarizeResponsesSseFrameForLogForHttpImpl,
  updateResponsesContractProbeFromSseChunkForHttp as updateResponsesContractProbeFromSseChunkForHttpImpl,
} from './responses-response-bridge.js';

export type { ResponsesRequestContextForHttp };

export const assertDirectPassthroughResponsesSseFrameForHttp = assertDirectPassthroughResponsesSseFrameForHttpImpl;
export const assertDirectPassthroughResponsesSseMetadataIsolationForHttp = assertDirectPassthroughResponsesSseMetadataIsolationForHttpImpl;
export const buildClientSseKeepaliveFrameForHttp = buildClientSseKeepaliveFrameForHttpImpl;
export const buildResponsesMissingSseBridgeErrorPayloadForHttp = buildResponsesMissingSseBridgeErrorPayloadForHttpImpl;
export const buildResponsesPayloadFromChatForHttp = buildResponsesPayloadFromChatForHttpImpl;
export const buildResponsesRequestLogContextForHttp = buildResponsesRequestLogContextForHttpImpl;
export const buildResponsesSseErrorPayloadForHttp = buildResponsesSseErrorPayloadForHttpImpl;
export const buildResponsesStreamIncompleteErrorPayloadForHttp = buildResponsesStreamIncompleteErrorPayloadForHttpImpl;
export const buildResponsesStructuredSseErrorPayloadForHttp = buildResponsesStructuredSseErrorPayloadForHttpImpl;
export const buildResponsesTerminalSseFramesFromProbeForHttp = buildResponsesTerminalSseFramesFromProbeForHttpImpl;
export const createResponsesJsonToSseConverterForHttp = createResponsesJsonToSseConverterForHttpImpl;
export const hasResponsesSsePayloadForHttp = hasResponsesSsePayloadForHttpImpl;
export const importResponsesHandlerCoreDist = importResponsesHandlerCoreDistImpl;
export const inspectResponsesContinuationProbeForHttp = inspectResponsesContinuationProbeForHttpImpl;
export const inspectResponsesTerminalStateFromSseChunkForHttp = inspectResponsesTerminalStateFromSseChunkForHttpImpl;
export const isDirectPassthroughTransportKeepaliveFrameForHttp = isDirectPassthroughTransportKeepaliveFrameForHttpImpl;
export const isToolCallContinuationResponseForHttp = isToolCallContinuationResponseForHttpImpl;
export const normalizeChatUsagePayloadForHttp = normalizeChatUsagePayloadForHttpImpl;
export const normalizeResponsesClientPayloadForHttp = normalizeResponsesClientPayloadForHttpImpl;
export const normalizeResponsesJsonBodyForHttp = normalizeResponsesJsonBodyForHttpImpl;
export const normalizeResponsesSseFrameForClientForHttp = normalizeResponsesSseFrameForClientForHttpImpl;
export const planResponsesContinuationCloseActionForHttp = planResponsesContinuationCloseActionForHttpImpl;
export const planResponsesStreamEndRepairForHttp = planResponsesStreamEndRepairForHttpImpl;
export const prepareResponsesJsonBodyForSseBridgeForHttp = prepareResponsesJsonBodyForSseBridgeForHttpImpl;
export const prepareResponsesJsonClientDispatchPlanForHttp = prepareResponsesJsonClientDispatchPlanForHttpImpl;
export const prepareResponsesJsonSseDispatchPlanForHttp = prepareResponsesJsonSseDispatchPlanForHttpImpl;
export const projectResponsesClientPayloadForClientForHttp = projectResponsesClientPayloadForClientForHttpImpl;
export const projectResponsesSseFrameForClientForHttp = projectResponsesSseFrameForClientForHttpImpl;
export const requireResponsesHandlerCoreDist = requireResponsesHandlerCoreDistImpl;
export const resolveResponsesClientPayloadFinishReasonForHttp = resolveResponsesClientPayloadFinishReasonForHttpImpl;
export const resolveResponsesProviderProtocolHintFromSseFrameForHttp = resolveResponsesProviderProtocolHintFromSseFrameForHttpImpl;
export const resolveResponsesRequestContextForHttp = resolveResponsesRequestContextForHttpImpl;
export const resolveResponsesTerminalProbeFinishReasonForHttp = resolveResponsesTerminalProbeFinishReasonForHttpImpl;
export const shouldDispatchResponsesSseToClientForHttp = shouldDispatchResponsesSseToClientForHttpImpl;
export const shouldDropClientSseFrameForHttp = shouldDropClientSseFrameForHttpImpl;
export const shouldPersistResponsesContinuationOnProbeUpdateForHttp = shouldPersistResponsesContinuationOnProbeUpdateForHttpImpl;
export const shouldPersistResponsesConversationStateForHttp = shouldPersistResponsesConversationStateForHttpImpl;
export const shouldRepairResponsesContinuationTerminalForHttp = shouldRepairResponsesContinuationTerminalForHttpImpl;
export const shouldRequireResponsesTerminalEventForHttp = shouldRequireResponsesTerminalEventForHttpImpl;
export const summarizeResponsesSseFrameForLogForHttp = summarizeResponsesSseFrameForLogForHttpImpl;
export const updateResponsesContractProbeFromSseChunkForHttp = updateResponsesContractProbeFromSseChunkForHttpImpl;
