/**
 * /v1/responses SSE-side handler bridge surface.
 *
 * Dedicated SSE projection-facing facade for responses SSE/JSON streaming
 * behaviors. Lifecycle persistence stays in responses-response-bridge.ts.
 */
import type { ResponsesRequestContextForHttp } from './responses-response-bridge.js';
import { buildResponsesMissingSseBridgeErrorPayloadForHttp as buildResponsesMissingSseBridgeErrorPayloadForHttpImpl, buildResponsesPayloadFromChatForHttp as buildResponsesPayloadFromChatForHttpImpl, buildResponsesRequestLogContextForHttp as buildResponsesRequestLogContextForHttpImpl, buildResponsesSseErrorPayloadForHttp as buildResponsesSseErrorPayloadForHttpImpl, buildResponsesStructuredSseErrorPayloadForHttp as buildResponsesStructuredSseErrorPayloadForHttpImpl, createChatJsonToSseConverterForHttp as createChatJsonToSseConverterForHttpImpl, importResponsesHandlerCoreDist as importResponsesHandlerCoreDistImpl, normalizeChatUsagePayloadForHttp as normalizeChatUsagePayloadForHttpImpl, prepareResponsesJsonBodyForSseBridgeForHttp as prepareResponsesJsonBodyForSseBridgeForHttpImpl, prepareResponsesJsonClientDispatchPlanForHttp as prepareResponsesJsonClientDispatchPlanForHttpImpl, prepareResponsesJsonSseDispatchPlanForHttp as prepareResponsesJsonSseDispatchPlanForHttpImpl, requireResponsesHandlerCoreDist as requireResponsesHandlerCoreDistImpl, resolveResponsesClientPayloadFinishReasonForHttp as resolveResponsesClientPayloadFinishReasonForHttpImpl, resolveResponsesRequestContextForHttp as resolveResponsesRequestContextForHttpImpl, resolveRelayResponsesClientSseStreamForHttp as resolveRelayResponsesClientSseStreamForHttpImpl, shouldDispatchResponsesSseToClientForHttp as shouldDispatchResponsesSseToClientForHttpImpl, shouldReprojectRelayResponsesSseForHttp as shouldReprojectRelayResponsesSseForHttpImpl } from './responses-response-bridge.js';
import { buildClientSseKeepaliveFrameForHttp as buildClientSseKeepaliveFrameForHttpImpl, createResponsesJsonToSseConverterForHttp as createResponsesJsonToSseConverterForHttpImpl, normalizeResponsesSseFrameForClientForHttp as normalizeResponsesSseFrameForClientForHttpImpl, projectResponsesSseFrameForClientForHttp as projectResponsesSseFrameForClientForHttpImpl, resolveResponsesProviderProtocolHintFromSseFrameForHttp as resolveResponsesProviderProtocolHintFromSseFrameForHttpImpl, shouldDropClientSseFrameForHttp as shouldDropClientSseFrameForHttpImpl, summarizeResponsesSseFrameForLogForHttp as summarizeResponsesSseFrameForLogForHttpImpl } from './responses-sse-semantics.js';
export type { ResponsesRequestContextForHttp };
export declare const buildClientSseKeepaliveFrameForHttp: typeof buildClientSseKeepaliveFrameForHttpImpl;
export declare const buildResponsesMissingSseBridgeErrorPayloadForHttp: typeof buildResponsesMissingSseBridgeErrorPayloadForHttpImpl;
export declare const buildResponsesPayloadFromChatForHttp: typeof buildResponsesPayloadFromChatForHttpImpl;
export declare const buildResponsesRequestLogContextForHttp: typeof buildResponsesRequestLogContextForHttpImpl;
export declare const buildResponsesSseErrorPayloadForHttp: typeof buildResponsesSseErrorPayloadForHttpImpl;
export declare const buildResponsesStructuredSseErrorPayloadForHttp: typeof buildResponsesStructuredSseErrorPayloadForHttpImpl;
export declare const createChatJsonToSseConverterForHttp: typeof createChatJsonToSseConverterForHttpImpl;
export declare const createResponsesJsonToSseConverterForHttp: typeof createResponsesJsonToSseConverterForHttpImpl;
export declare const importResponsesHandlerCoreDist: typeof importResponsesHandlerCoreDistImpl;
export declare const normalizeChatUsagePayloadForHttp: typeof normalizeChatUsagePayloadForHttpImpl;
export declare const normalizeResponsesSseFrameForClientForHttp: typeof normalizeResponsesSseFrameForClientForHttpImpl;
export declare const prepareResponsesJsonBodyForSseBridgeForHttp: typeof prepareResponsesJsonBodyForSseBridgeForHttpImpl;
export declare const prepareResponsesJsonClientDispatchPlanForHttp: typeof prepareResponsesJsonClientDispatchPlanForHttpImpl;
export declare const prepareResponsesJsonSseDispatchPlanForHttp: typeof prepareResponsesJsonSseDispatchPlanForHttpImpl;
export declare const projectResponsesSseFrameForClientForHttp: typeof projectResponsesSseFrameForClientForHttpImpl;
export declare const requireResponsesHandlerCoreDist: typeof requireResponsesHandlerCoreDistImpl;
export declare const resolveResponsesClientPayloadFinishReasonForHttp: typeof resolveResponsesClientPayloadFinishReasonForHttpImpl;
export declare const resolveResponsesProviderProtocolHintFromSseFrameForHttp: typeof resolveResponsesProviderProtocolHintFromSseFrameForHttpImpl;
export declare const resolveResponsesRequestContextForHttp: typeof resolveResponsesRequestContextForHttpImpl;
export declare const resolveRelayResponsesClientSseStreamForHttp: typeof resolveRelayResponsesClientSseStreamForHttpImpl;
export declare const shouldDispatchResponsesSseToClientForHttp: typeof shouldDispatchResponsesSseToClientForHttpImpl;
export declare const shouldDropClientSseFrameForHttp: typeof shouldDropClientSseFrameForHttpImpl;
export declare const shouldReprojectRelayResponsesSseForHttp: typeof shouldReprojectRelayResponsesSseForHttpImpl;
export declare const summarizeResponsesSseFrameForLogForHttp: typeof summarizeResponsesSseFrameForLogForHttpImpl;
export declare function reprojectDirectChatToolCallStreamForHttp(args: {
    body: Record<string, unknown>;
    requestId?: string;
}): Promise<import('node:stream').Readable>;
export declare function isDirectPassthroughTransportKeepaliveFrameForHttp(frame: string): boolean;
export declare function assertDirectPassthroughResponsesSseFrameForHttp(frame: string, requestId: string): void;
export declare function assertDirectPassthroughResponsesSseMetadataIsolationForHttp(frame: string, requestId: string): void;
export declare function sanitizeDirectPassthroughResponsesSseFrameForHttp(frame: string, _requestId: string): string;
