/**
 * /v1/responses SSE-side handler bridge surface.
 *
 * Dedicated SSE projection-facing facade for responses SSE/JSON streaming
 * behaviors. Lifecycle persistence stays in responses-response-bridge.ts.
 */

// feature_id: server.responses_sse_bridge_surface
// canonical_builders: shouldDispatchResponsesSseToClientForHttp, resolveResponsesRequestContextForHttp, assertDirectPassthroughResponsesSseMetadataIsolationForHttp, summarizeResponsesSseFrameForLogForHttp, resolveResponsesProviderProtocolHintFromSseFrameForHttp, buildResponsesSseErrorPayloadForHttp, buildResponsesStructuredSseErrorPayloadForHttp, buildResponsesMissingSseBridgeErrorPayloadForHttp, createResponsesJsonToSseConverterForHttp, prepareResponsesJsonBodyForSseBridgeForHttp, buildResponsesPayloadFromChatForHttp, normalizeResponsesSseFrameForClientForHttp

import type { ResponsesRequestContextForHttp } from './responses-response-bridge.js';
import {
  assertDirectPassthroughResponsesSseFrameForHttp as assertDirectPassthroughResponsesSseFrameForHttpImpl,
  assertDirectPassthroughResponsesSseMetadataIsolationForHttp as assertDirectPassthroughResponsesSseMetadataIsolationForHttpImpl,
  buildResponsesMissingSseBridgeErrorPayloadForHttp as buildResponsesMissingSseBridgeErrorPayloadForHttpImpl,
  buildResponsesPayloadFromChatForHttp as buildResponsesPayloadFromChatForHttpImpl,
  buildResponsesRequestLogContextForHttp as buildResponsesRequestLogContextForHttpImpl,
  buildResponsesSseErrorPayloadForHttp as buildResponsesSseErrorPayloadForHttpImpl,
  buildResponsesStructuredSseErrorPayloadForHttp as buildResponsesStructuredSseErrorPayloadForHttpImpl,
  createChatJsonToSseConverterForHttp as createChatJsonToSseConverterForHttpImpl,
  importResponsesHandlerCoreDist as importResponsesHandlerCoreDistImpl,
  isDirectPassthroughTransportKeepaliveFrameForHttp as isDirectPassthroughTransportKeepaliveFrameForHttpImpl,
  normalizeChatUsagePayloadForHttp as normalizeChatUsagePayloadForHttpImpl,
  prepareResponsesJsonBodyForSseBridgeForHttp as prepareResponsesJsonBodyForSseBridgeForHttpImpl,
  prepareResponsesJsonClientDispatchPlanForHttp as prepareResponsesJsonClientDispatchPlanForHttpImpl,
  prepareResponsesJsonSseDispatchPlanForHttp as prepareResponsesJsonSseDispatchPlanForHttpImpl,
  requireResponsesHandlerCoreDist as requireResponsesHandlerCoreDistImpl,
  resolveResponsesClientPayloadFinishReasonForHttp as resolveResponsesClientPayloadFinishReasonForHttpImpl,
  resolveResponsesRequestContextForHttp as resolveResponsesRequestContextForHttpImpl,
  resolveRelayResponsesClientSseStreamForHttp as resolveRelayResponsesClientSseStreamForHttpImpl,
  sanitizeDirectPassthroughResponsesSseFrameForHttp as sanitizeDirectPassthroughResponsesSseFrameForHttpImpl,
  shouldDispatchResponsesSseToClientForHttp as shouldDispatchResponsesSseToClientForHttpImpl,
  shouldReprojectRelayResponsesSseForHttp as shouldReprojectRelayResponsesSseForHttpImpl,
} from './responses-response-bridge.js';
import {
  buildClientSseKeepaliveFrameForHttp as buildClientSseKeepaliveFrameForHttpImpl,
  createResponsesJsonToSseConverterForHttp as createResponsesJsonToSseConverterForHttpImpl,
  normalizeResponsesSseFrameForClientForHttp as normalizeResponsesSseFrameForClientForHttpImpl,
  projectResponsesSseFrameForClientForHttp as projectResponsesSseFrameForClientForHttpImpl,
  resolveResponsesProviderProtocolHintFromSseFrameForHttp as resolveResponsesProviderProtocolHintFromSseFrameForHttpImpl,
  shouldDropClientSseFrameForHttp as shouldDropClientSseFrameForHttpImpl,
  summarizeResponsesSseFrameForLogForHttp as summarizeResponsesSseFrameForLogForHttpImpl,
} from './responses-sse-semantics.js';

export type { ResponsesRequestContextForHttp };

export const assertDirectPassthroughResponsesSseFrameForHttp = assertDirectPassthroughResponsesSseFrameForHttpImpl;
export const assertDirectPassthroughResponsesSseMetadataIsolationForHttp = assertDirectPassthroughResponsesSseMetadataIsolationForHttpImpl;
export const sanitizeDirectPassthroughResponsesSseFrameForHttp = sanitizeDirectPassthroughResponsesSseFrameForHttpImpl;
export const buildClientSseKeepaliveFrameForHttp = buildClientSseKeepaliveFrameForHttpImpl;
export const buildResponsesMissingSseBridgeErrorPayloadForHttp = buildResponsesMissingSseBridgeErrorPayloadForHttpImpl;
export const buildResponsesPayloadFromChatForHttp = buildResponsesPayloadFromChatForHttpImpl;
export const buildResponsesRequestLogContextForHttp = buildResponsesRequestLogContextForHttpImpl;
export const buildResponsesSseErrorPayloadForHttp = buildResponsesSseErrorPayloadForHttpImpl;
export const buildResponsesStructuredSseErrorPayloadForHttp = buildResponsesStructuredSseErrorPayloadForHttpImpl;
export const createChatJsonToSseConverterForHttp = createChatJsonToSseConverterForHttpImpl;
export const createResponsesJsonToSseConverterForHttp = createResponsesJsonToSseConverterForHttpImpl;
export const importResponsesHandlerCoreDist = importResponsesHandlerCoreDistImpl;
export const isDirectPassthroughTransportKeepaliveFrameForHttp = isDirectPassthroughTransportKeepaliveFrameForHttpImpl;
export const normalizeChatUsagePayloadForHttp = normalizeChatUsagePayloadForHttpImpl;
export const normalizeResponsesSseFrameForClientForHttp = normalizeResponsesSseFrameForClientForHttpImpl;
export const prepareResponsesJsonBodyForSseBridgeForHttp = prepareResponsesJsonBodyForSseBridgeForHttpImpl;
export const prepareResponsesJsonClientDispatchPlanForHttp = prepareResponsesJsonClientDispatchPlanForHttpImpl;
export const prepareResponsesJsonSseDispatchPlanForHttp = prepareResponsesJsonSseDispatchPlanForHttpImpl;
export const projectResponsesSseFrameForClientForHttp = projectResponsesSseFrameForClientForHttpImpl;
export const requireResponsesHandlerCoreDist = requireResponsesHandlerCoreDistImpl;
export const resolveResponsesClientPayloadFinishReasonForHttp = resolveResponsesClientPayloadFinishReasonForHttpImpl;
export const resolveResponsesProviderProtocolHintFromSseFrameForHttp = resolveResponsesProviderProtocolHintFromSseFrameForHttpImpl;
export const resolveResponsesRequestContextForHttp = resolveResponsesRequestContextForHttpImpl;
export const resolveRelayResponsesClientSseStreamForHttp = resolveRelayResponsesClientSseStreamForHttpImpl;
export const shouldDispatchResponsesSseToClientForHttp = shouldDispatchResponsesSseToClientForHttpImpl;
export const shouldDropClientSseFrameForHttp = shouldDropClientSseFrameForHttpImpl;
export const shouldReprojectRelayResponsesSseForHttp = shouldReprojectRelayResponsesSseForHttpImpl;
export const summarizeResponsesSseFrameForLogForHttp = summarizeResponsesSseFrameForLogForHttpImpl;
