// Auto-generated by scripts/gen-build-info.mjs
export interface BuildInfo { mode: 'dev' | 'release'; version: string; buildTime: string }
export const buildInfo: BuildInfo = {
  mode: 'release',
  version: '0.90.3982',
  buildTime: '2026-07-25T11:14:25.320Z'
};
