// Auto-generated by scripts/gen-build-info.mjs
export interface BuildInfo { mode: 'dev' | 'release'; version: string; buildTime: string }
export const buildInfo: BuildInfo = {
  mode: 'dev',
  version: '0.90.207',
  buildTime: '2026-03-08T04:37:20.286Z'
};
