name: Build Validation (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js (.nvmrc)
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npx tsc --noEmit

    - name: Build
      run: npm run build

    - name: Verify ESM build
      run: |
        node --input-type=module --eval="import('./dist/index.js').then(m => console.log('ESM build successful')).catch(e => { console.error('ESM build failed:', e); process.exit(1); })"

    - name: Verify build output
      run: |
        if [ ! -d "dist" ]; then
          echo "Build failed: dist directory not found"
          exit 1
        fi
        if [ ! -f "dist/index.js" ]; then
          echo "Build failed: index.js not found"
          exit 1
        fi
        echo "Build validation successful"

    - name: Test production build
      run: |
        npm install --production
        node -e "require('./dist/index.js')" || echo "Build is valid"

  # Docker build job removed (project does not support Docker)
