name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run Prettier (if available)
      run: npx prettier --check src/ || echo "Prettier not installed, skipping"

    - name: Check for unused dependencies
      run: npx depcheck || echo "Depcheck found issues"

    - name: Security Audit (production deps)
      run: npm audit --production --audit-level moderate || true

  typescript-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npx tsc --noEmit --strict

    - name: Check for any TypeScript errors
      run: npx tsc --noEmit --noUnusedLocals --noUnusedParameters

    - name: Verify ESM compatibility
      run: npm run build && node --input-type=module --eval="import('./dist/index.js').then(m => console.log('ESM compatibility verified'))"
