name: Duplication Report

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  duplication-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run duplication scan
        run: npm run dup:scan || true

      - name: Upload duplication report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: duplication-report
          path: reports/*.json
          if-no-files-found: ignore

